import React, { useState, useEffect, useRef } from 'react';
import { base44 } from '@/api/base44Client';
import { Button } from '@/components/ui/button';
import { Sparkles, Loader2, RefreshCw, TrendingUp, Lightbulb, BookOpen, ChevronDown, ChevronUp } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import { DASHBOARD_ASSETS, DASHBOARD_ASSET_MAP } from '@/lib/dashboardAssets';

function Section({ icon: Icon, title, color, children }) {
  const [open, setOpen] = useState(true);
  return (
    <div className="border border-slate-800 rounded-xl overflow-hidden">
      <button
        onClick={() => setOpen(o => !o)}
        className="w-full flex items-center justify-between px-4 py-3 bg-slate-900/60 hover:bg-slate-800/40 transition-colors"
      >
        <div className="flex items-center gap-2">
          <Icon className={`w-3.5 h-3.5 ${color}`} />
          <span className={`text-[10px] font-mono uppercase tracking-widest ${color}`}>{title}</span>
        </div>
        {open ? <ChevronUp className="w-3.5 h-3.5 text-slate-600" /> : <ChevronDown className="w-3.5 h-3.5 text-slate-600" />}
      </button>
      {open && (
        <div className="px-4 py-3 bg-slate-900/20">
          <ReactMarkdown className="prose prose-sm prose-invert max-w-none [&>*:first-child]:mt-0 [&>*:last-child]:mb-0 [&_p]:my-1.5 [&_ul]:my-1.5 [&_li]:my-0.5 [&_strong]:text-slate-100 [&_p]:text-slate-300 [&_li]:text-slate-300 text-sm leading-relaxed">
            {children}
          </ReactMarkdown>
        </div>
      )}
    </div>
  );
}

async function fetchScanData() {
  const symbols = DASHBOARD_ASSETS.map(a => a.symbol);
  let all = [];
  for (let i = 0; i < symbols.length; i += 30) {
    try {
      const res = await base44.functions.invoke('runScreener', { symbols: symbols.slice(i, i + 30) });
      all = [...all, ...(res.data?.results || [])];
    } catch (e) { console.error(e); }
  }
  return all.map(r => ({
    ...r,
    name: DASHBOARD_ASSET_MAP[r.symbol]?.name || r.symbol,
    sector: DASHBOARD_ASSET_MAP[r.symbol]?.sector || '',
    index: DASHBOARD_ASSET_MAP[r.symbol]?.index || '',
  }));
}

export default function AiInsightsPanel({ autoGenerate = false }) {
  const [insights, setInsights] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const hasAutoGenerated = useRef(false);

  useEffect(() => {
    if (autoGenerate && !hasAutoGenerated.current) {
      hasAutoGenerated.current = true;
      generate();
    }
  }, [autoGenerate]);

  const generate = async () => {
    if (loading) return;
    setLoading(true);
    setInsights(null);
    setError(null);

    try {
      const results = await fetchScanData();

      const signalCounts = results.reduce((acc, r) => { acc[r.signal] = (acc[r.signal] || 0) + 1; return acc; }, {});
      const topBuys = results
        .filter(r => r.rsi != null && r.rsi <= 40)
        .sort((a, b) => (a.rsi ?? 99) - (b.rsi ?? 99))
        .slice(0, 8)
        .map(r => `${r.symbol}(${r.index}): RSI=${r.rsi?.toFixed(0)}, EMA=${r.ema_signal}, MACD=${r.macd_signal}, chg=${r.change_pct?.toFixed(1)}%`);
      const topSells = results
        .filter(r => r.rsi != null && r.rsi >= 60)
        .sort((a, b) => (b.rsi ?? 0) - (a.rsi ?? 0))
        .slice(0, 6)
        .map(r => `${r.symbol}(${r.index}): RSI=${r.rsi?.toFixed(0)}, chg=${r.change_pct?.toFixed(1)}%`);
      const cryptoResults = results.filter(r => r.index === 'CLARITY');
      const cryptoBias = cryptoResults.map(r => `${r.symbol}: RSI=${r.rsi?.toFixed(0)}, chg=${r.change_pct?.toFixed(1)}%`).join(' | ');

      const prompt = `You are an expert quantitative analyst monitoring S&P 500, Nasdaq 100, Dow Jones, and CLARITY Act crypto assets. Analyze this live screener data and provide actionable insights in exactly 3 sections.

UNIVERSE: ${results.length} assets scanned (S&P 500 blue chips, Nasdaq 100, Dow Jones 30, CLARITY Act crypto)
Signal breakdown: ${JSON.stringify(signalCounts)}

TOP OVERSOLD (RSI ≤40, potential BUY): ${topBuys.join(' | ') || 'none'}
TOP OVERBOUGHT (RSI ≥60, potential SELL): ${topSells.join(' | ') || 'none'}
CLARITY ACT CRYPTO: ${cryptoBias || 'no data'}

Provide exactly these 3 sections (markdown, concise, data-driven):

## Market Sentiment
2–3 sentences summarizing the overall market tone across equities (S&P, Nasdaq, Dow) and crypto. Is money rotating? Risk-on or risk-off? Any index divergence?

## Trading Strategies
4–6 specific, actionable setups. Reference symbols and indices. Include entry logic (e.g. "Add SPY on this dip — RSI=38 with Dow holding above key support"), risk/reward context, and at least 1 crypto CLARITY Act trade if signals exist.

## Why These Signals
Explain the top 3 standout signals in plain English. What is RSI, EMA, and MACD confluence telling us right now across these major indices and crypto assets?`;

      const response = await base44.integrations.Core.InvokeLLM({ prompt, model: 'claude_sonnet_4_6' });
      const text = typeof response === 'string' ? response : JSON.stringify(response);

      const sections = {
        sentiment: text.match(/## Market Sentiment\n([\s\S]*?)(?=## |$)/)?.[1]?.trim() || '',
        strategies: text.match(/## Trading Strategies\n([\s\S]*?)(?=## |$)/)?.[1]?.trim() || '',
        signals: text.match(/## Why These Signals\n([\s\S]*?)(?=## |$)/)?.[1]?.trim() || '',
      };

      setInsights(sections);
    } catch (e) {
      console.error('AiInsightsPanel error:', e);
      setError('Failed to generate insights — network issue. Please try again.');
    }

    setLoading(false);
  };

  return (
    <div className="bg-slate-900/40 border border-slate-800 rounded-xl overflow-hidden">
      {/* Header */}
      <div className="px-4 py-3 border-b border-slate-800 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <div className="w-6 h-6 rounded-lg bg-gradient-to-br from-purple-600 to-blue-600 flex items-center justify-center">
            <Sparkles className="w-3.5 h-3.5 text-white" />
          </div>
          <div>
            <span className="text-sm font-semibold text-slate-100">AI Market Insights</span>
            <span className="ml-2 text-[10px] text-slate-600 font-mono">S&P 500 · Nasdaq · Dow · CLARITY Crypto</span>
          </div>
        </div>
        <Button
          size="sm"
          onClick={generate}
          disabled={loading}
          className={`text-xs ${insights ? 'bg-slate-800 hover:bg-slate-700 text-slate-300 border border-slate-700' : 'bg-gradient-to-r from-purple-600 to-blue-600 hover:from-purple-700 hover:to-blue-700 text-white'}`}
        >
          {loading
            ? <><Loader2 className="w-3.5 h-3.5 mr-1.5 animate-spin" />Analysing…</>
            : insights
            ? <><RefreshCw className="w-3.5 h-3.5 mr-1.5" />Refresh</>
            : <><Sparkles className="w-3.5 h-3.5 mr-1.5" />Generate Insights</>
          }
        </Button>
      </div>

      {/* Body */}
      <div className="p-4">
        {error && !loading && (
          <div className="text-center py-8">
            <p className="text-red-400 text-sm mb-2">{error}</p>
            <Button size="sm" onClick={generate} className="text-xs bg-slate-800 hover:bg-slate-700 text-slate-300 border border-slate-700">
              <RefreshCw className="w-3.5 h-3.5 mr-1.5" />Retry
            </Button>
          </div>
        )}

        {!insights && !loading && !error && (
          <div className="text-center py-8">
            <Sparkles className="w-10 h-10 text-slate-700 mx-auto mb-3" />
            <p className="text-slate-500 text-sm mb-1">AI insights not generated yet</p>
            <p className="text-slate-700 text-xs font-mono">
              Scans S&P 500, Nasdaq 100, Dow Jones & CLARITY Act crypto — click "Generate Insights"
            </p>
          </div>
        )}

        {loading && (
          <div className="space-y-3">
            {[...Array(3)].map((_, i) => (
              <div key={i} className="border border-slate-800 rounded-xl overflow-hidden animate-pulse">
                <div className="h-10 bg-slate-800/60" />
                <div className="p-4 space-y-2">
                  <div className="h-3 bg-slate-800 rounded w-3/4" />
                  <div className="h-3 bg-slate-800 rounded w-full" />
                  <div className="h-3 bg-slate-800 rounded w-5/6" />
                </div>
              </div>
            ))}
          </div>
        )}

        {insights && !loading && (
          <div className="space-y-3">
            {insights.sentiment && (
              <Section icon={TrendingUp} title="Market Sentiment" color="text-blue-400">
                {insights.sentiment}
              </Section>
            )}
            {insights.strategies && (
              <Section icon={Lightbulb} title="Trading Strategies" color="text-emerald-400">
                {insights.strategies}
              </Section>
            )}
            {insights.signals && (
              <Section icon={BookOpen} title="Why These Signals" color="text-amber-400">
                {insights.signals}
              </Section>
            )}
          </div>
        )}
      </div>
    </div>
  );
}