// Comprehensive asset catalog — top stocks by exchange + crypto
// congress_flagged = known congressional trading activity

export const ASSETS = [
  // ── NASDAQ ──────────────────────────────────────────────────────────────────
  { symbol: 'AAPL',  name: 'Apple Inc.',               exchange: 'NASDAQ', sector: 'Technology',    asset_type: 'stock', congress_flagged: true  },
  { symbol: 'MSFT',  name: 'Microsoft Corp.',           exchange: 'NASDAQ', sector: 'Technology',    asset_type: 'stock', congress_flagged: true  },
  { symbol: 'NVDA',  name: 'NVIDIA Corp.',              exchange: 'NASDAQ', sector: 'Semiconductors',asset_type: 'stock', congress_flagged: true  },
  { symbol: 'AMZN',  name: 'Amazon.com Inc.',           exchange: 'NASDAQ', sector: 'E-Commerce',    asset_type: 'stock', congress_flagged: true  },
  { symbol: 'META',  name: 'Meta Platforms',            exchange: 'NASDAQ', sector: 'Technology',    asset_type: 'stock', congress_flagged: true  },
  { symbol: 'GOOGL', name: 'Alphabet Inc. (A)',         exchange: 'NASDAQ', sector: 'Technology',    asset_type: 'stock', congress_flagged: true  },
  { symbol: 'GOOG',  name: 'Alphabet Inc. (C)',         exchange: 'NASDAQ', sector: 'Technology',    asset_type: 'stock', congress_flagged: false },
  { symbol: 'TSLA',  name: 'Tesla Inc.',                exchange: 'NASDAQ', sector: 'Automotive',    asset_type: 'stock', congress_flagged: true  },
  { symbol: 'NFLX',  name: 'Netflix Inc.',              exchange: 'NASDAQ', sector: 'Media',         asset_type: 'stock', congress_flagged: false },
  { symbol: 'ADBE',  name: 'Adobe Inc.',                exchange: 'NASDAQ', sector: 'Software',      asset_type: 'stock', congress_flagged: false },
  { symbol: 'CRM',   name: 'Salesforce Inc.',           exchange: 'NASDAQ', sector: 'Software',      asset_type: 'stock', congress_flagged: false },
  { symbol: 'AMD',   name: 'Advanced Micro Devices',    exchange: 'NASDAQ', sector: 'Semiconductors',asset_type: 'stock', congress_flagged: true  },
  { symbol: 'INTC',  name: 'Intel Corp.',               exchange: 'NASDAQ', sector: 'Semiconductors',asset_type: 'stock', congress_flagged: true  },
  { symbol: 'QCOM',  name: 'Qualcomm Inc.',             exchange: 'NASDAQ', sector: 'Semiconductors',asset_type: 'stock', congress_flagged: false },
  { symbol: 'AVGO',  name: 'Broadcom Inc.',             exchange: 'NASDAQ', sector: 'Semiconductors',asset_type: 'stock', congress_flagged: false },
  { symbol: 'AMAT',  name: 'Applied Materials',         exchange: 'NASDAQ', sector: 'Semiconductors',asset_type: 'stock', congress_flagged: false },
  { symbol: 'LRCX',  name: 'Lam Research Corp.',        exchange: 'NASDAQ', sector: 'Semiconductors',asset_type: 'stock', congress_flagged: false },
  { symbol: 'MU',    name: 'Micron Technology',         exchange: 'NASDAQ', sector: 'Semiconductors',asset_type: 'stock', congress_flagged: true  },
  { symbol: 'TXN',   name: 'Texas Instruments',         exchange: 'NASDAQ', sector: 'Semiconductors',asset_type: 'stock', congress_flagged: false },
  { symbol: 'MRVL',  name: 'Marvell Technology',        exchange: 'NASDAQ', sector: 'Semiconductors',asset_type: 'stock', congress_flagged: false },
  { symbol: 'SMCI',  name: 'Super Micro Computer',      exchange: 'NASDAQ', sector: 'Technology',    asset_type: 'stock', congress_flagged: false },
  { symbol: 'ASML',  name: 'ASML Holding NV',           exchange: 'NASDAQ', sector: 'Semiconductors',asset_type: 'stock', congress_flagged: false },
  { symbol: 'TSM',   name: 'TSMC (Taiwan Semiconductor)',exchange: 'NYSE',  sector: 'Semiconductors',asset_type: 'stock', congress_flagged: false },
  { symbol: 'CSCO',  name: 'Cisco Systems',             exchange: 'NASDAQ', sector: 'Networking',    asset_type: 'stock', congress_flagged: false },
  { symbol: 'IBM',   name: 'IBM Corp.',                 exchange: 'NYSE',   sector: 'Technology',    asset_type: 'stock', congress_flagged: false },
  { symbol: 'ANET',  name: 'Arista Networks',           exchange: 'NYSE',   sector: 'Networking',    asset_type: 'stock', congress_flagged: false },
  { symbol: 'AMGN',  name: 'Amgen Inc.',               exchange: 'NASDAQ', sector: 'Biotech',       asset_type: 'stock', congress_flagged: false },
  { symbol: 'ORCL',  name: 'Oracle Corp.',              exchange: 'NYSE',   sector: 'Software',      asset_type: 'stock', congress_flagged: false },
  { symbol: 'PYPL',  name: 'PayPal Holdings',           exchange: 'NASDAQ', sector: 'Fintech',       asset_type: 'stock', congress_flagged: false },
  { symbol: 'PLTR',  name: 'Palantir Technologies',     exchange: 'NASDAQ', sector: 'AI/Data',       asset_type: 'stock', congress_flagged: true  },
  { symbol: 'SNOW',  name: 'Snowflake Inc.',            exchange: 'NYSE',   sector: 'Cloud',         asset_type: 'stock', congress_flagged: true  },
  { symbol: 'DDOG',  name: 'Datadog Inc.',              exchange: 'NASDAQ', sector: 'Cloud',         asset_type: 'stock', congress_flagged: false },
  { symbol: 'CRWD',  name: 'CrowdStrike Holdings',      exchange: 'NASDAQ', sector: 'Cybersecurity', asset_type: 'stock', congress_flagged: true  },
  { symbol: 'ZS',    name: 'Zscaler Inc.',              exchange: 'NASDAQ', sector: 'Cybersecurity', asset_type: 'stock', congress_flagged: false },
  { symbol: 'NET',   name: 'Cloudflare Inc.',           exchange: 'NYSE',   sector: 'Cybersecurity', asset_type: 'stock', congress_flagged: false },
  { symbol: 'PANW',  name: 'Palo Alto Networks',        exchange: 'NASDAQ', sector: 'Cybersecurity', asset_type: 'stock', congress_flagged: false },
  { symbol: 'FTNT',  name: 'Fortinet Inc.',             exchange: 'NASDAQ', sector: 'Cybersecurity', asset_type: 'stock', congress_flagged: false },
  { symbol: 'S',     name: 'SentinelOne Inc.',          exchange: 'NYSE',   sector: 'Cybersecurity', asset_type: 'stock', congress_flagged: false },
  { symbol: 'ABNB',  name: 'Airbnb Inc.',               exchange: 'NASDAQ', sector: 'Travel',        asset_type: 'stock', congress_flagged: false },
  { symbol: 'DASH',  name: 'DoorDash Inc.',             exchange: 'NYSE',   sector: 'Delivery',      asset_type: 'stock', congress_flagged: false },
  { symbol: 'UBER',  name: 'Uber Technologies',         exchange: 'NYSE',   sector: 'Mobility',      asset_type: 'stock', congress_flagged: false },
  { symbol: 'LYFT',  name: 'Lyft Inc.',                 exchange: 'NASDAQ', sector: 'Mobility',      asset_type: 'stock', congress_flagged: false },
  { symbol: 'SPOT',  name: 'Spotify Technology',        exchange: 'NYSE',   sector: 'Media',         asset_type: 'stock', congress_flagged: false },
  { symbol: 'PINS',  name: 'Pinterest Inc.',            exchange: 'NYSE',   sector: 'Social Media',  asset_type: 'stock', congress_flagged: false },
  { symbol: 'SNAP',  name: 'Snap Inc.',                 exchange: 'NYSE',   sector: 'Social Media',  asset_type: 'stock', congress_flagged: false },
  { symbol: 'TTD',   name: 'The Trade Desk',            exchange: 'NASDAQ', sector: 'AdTech',        asset_type: 'stock', congress_flagged: false },
  { symbol: 'RBLX',  name: 'Roblox Corp.',              exchange: 'NYSE',   sector: 'Gaming',        asset_type: 'stock', congress_flagged: true  },
  { symbol: 'COIN',  name: 'Coinbase Global',           exchange: 'NASDAQ', sector: 'Crypto',        asset_type: 'stock', congress_flagged: true  },
  { symbol: 'MSTR',  name: 'MicroStrategy Inc.',        exchange: 'NASDAQ', sector: 'Crypto',        asset_type: 'stock', congress_flagged: false },
  { symbol: 'HOOD',  name: 'Robinhood Markets',         exchange: 'NASDAQ', sector: 'Fintech',       asset_type: 'stock', congress_flagged: false },
  { symbol: 'SOFI',  name: 'SoFi Technologies',         exchange: 'NASDAQ', sector: 'Fintech',       asset_type: 'stock', congress_flagged: false },
  { symbol: 'AFRM',  name: 'Affirm Holdings',           exchange: 'NASDAQ', sector: 'Fintech',       asset_type: 'stock', congress_flagged: false },
  { symbol: 'UPST',  name: 'Upstart Holdings',          exchange: 'NASDAQ', sector: 'Fintech',       asset_type: 'stock', congress_flagged: false },
  { symbol: 'IONQ',  name: 'IonQ Inc.',                 exchange: 'NYSE',   sector: 'Quantum',       asset_type: 'stock', congress_flagged: true  },
  { symbol: 'RGTI',  name: 'Rigetti Computing',         exchange: 'NASDAQ', sector: 'Quantum',       asset_type: 'stock', congress_flagged: false },
  { symbol: 'QBTS',  name: 'D-Wave Quantum',            exchange: 'NYSE',   sector: 'Quantum',       asset_type: 'stock', congress_flagged: false },
  { symbol: 'AI',    name: 'C3.ai Inc.',                exchange: 'NYSE',   sector: 'AI',            asset_type: 'stock', congress_flagged: false },
  { symbol: 'SOUN',  name: 'SoundHound AI',             exchange: 'NASDAQ', sector: 'AI',            asset_type: 'stock', congress_flagged: false },
  { symbol: 'BBAI',  name: 'BigBear.ai Holdings',       exchange: 'NYSE',   sector: 'AI',            asset_type: 'stock', congress_flagged: false },
  { symbol: 'RXRX',  name: 'Recursion Pharma',          exchange: 'NASDAQ', sector: 'BioAI',         asset_type: 'stock', congress_flagged: false },
  { symbol: 'PATH',  name: 'UiPath Inc.',               exchange: 'NYSE',   sector: 'Automation',    asset_type: 'stock', congress_flagged: false },
  { symbol: 'APPN',  name: 'Appian Corp.',              exchange: 'NASDAQ', sector: 'Software',      asset_type: 'stock', congress_flagged: false },
  { symbol: 'BILL',  name: 'Bill.com Holdings',         exchange: 'NYSE',   sector: 'Fintech',       asset_type: 'stock', congress_flagged: false },
  { symbol: 'MDB',   name: 'MongoDB Inc.',              exchange: 'NASDAQ', sector: 'Database',      asset_type: 'stock', congress_flagged: false },
  { symbol: 'ESTC',  name: 'Elastic NV',               exchange: 'NYSE',   sector: 'Database',      asset_type: 'stock', congress_flagged: false },
  { symbol: 'GTLB',  name: 'GitLab Inc.',              exchange: 'NASDAQ', sector: 'DevOps',         asset_type: 'stock', congress_flagged: false },
  { symbol: 'HUBS',  name: 'HubSpot Inc.',             exchange: 'NYSE',   sector: 'SaaS',           asset_type: 'stock', congress_flagged: false },
  { symbol: 'WDAY',  name: 'Workday Inc.',             exchange: 'NASDAQ', sector: 'HCM Software',   asset_type: 'stock', congress_flagged: false },
  { symbol: 'NOW',   name: 'ServiceNow Inc.',          exchange: 'NYSE',   sector: 'Software',       asset_type: 'stock', congress_flagged: true  },
  { symbol: 'ZM',    name: 'Zoom Video',               exchange: 'NASDAQ', sector: 'Communications', asset_type: 'stock', congress_flagged: false },
  { symbol: 'DOCU',  name: 'DocuSign Inc.',            exchange: 'NASDAQ', sector: 'Software',       asset_type: 'stock', congress_flagged: false },
  { symbol: 'TWLO',  name: 'Twilio Inc.',              exchange: 'NYSE',   sector: 'Communications', asset_type: 'stock', congress_flagged: false },
  { symbol: 'U',     name: 'Unity Software',           exchange: 'NYSE',   sector: 'Gaming/3D',      asset_type: 'stock', congress_flagged: false },
  { symbol: 'BMBL',  name: 'Bumble Inc.',              exchange: 'NASDAQ', sector: 'Social',         asset_type: 'stock', congress_flagged: false },
  { symbol: 'RIVN',  name: 'Rivian Automotive',        exchange: 'NASDAQ', sector: 'EV',             asset_type: 'stock', congress_flagged: true  },
  { symbol: 'LCID',  name: 'Lucid Group Inc.',         exchange: 'NASDAQ', sector: 'EV',             asset_type: 'stock', congress_flagged: false },
  { symbol: 'NIO',   name: 'NIO Inc.',                 exchange: 'NYSE',   sector: 'EV',             asset_type: 'stock', congress_flagged: false },
  { symbol: 'XPEV',  name: 'XPeng Inc.',               exchange: 'NYSE',   sector: 'EV',             asset_type: 'stock', congress_flagged: false },
  { symbol: 'LI',    name: 'Li Auto Inc.',             exchange: 'NASDAQ', sector: 'EV',             asset_type: 'stock', congress_flagged: false },
  { symbol: 'CHPT',  name: 'ChargePoint Holdings',     exchange: 'NYSE',   sector: 'EV Infra',       asset_type: 'stock', congress_flagged: false },
  { symbol: 'BLDP',  name: 'Ballard Power Systems',    exchange: 'NASDAQ', sector: 'Clean Energy',   asset_type: 'stock', congress_flagged: false },
  { symbol: 'ENPH',  name: 'Enphase Energy',           exchange: 'NASDAQ', sector: 'Solar',          asset_type: 'stock', congress_flagged: false },
  { symbol: 'SEDG',  name: 'SolarEdge Technologies',   exchange: 'NASDAQ', sector: 'Solar',          asset_type: 'stock', congress_flagged: false },
  { symbol: 'FSLR',  name: 'First Solar Inc.',         exchange: 'NASDAQ', sector: 'Solar',          asset_type: 'stock', congress_flagged: false },
  { symbol: 'PLUG',  name: 'Plug Power Inc.',          exchange: 'NASDAQ', sector: 'Hydrogen',       asset_type: 'stock', congress_flagged: false },
  { symbol: 'OKTA',  name: 'Okta Inc.',                exchange: 'NASDAQ', sector: 'Identity',       asset_type: 'stock', congress_flagged: false },
  { symbol: 'SPLK',  name: 'Splunk Inc.',              exchange: 'NASDAQ', sector: 'Security',       asset_type: 'stock', congress_flagged: false },
  { symbol: 'VEEV',  name: 'Veeva Systems',            exchange: 'NYSE',   sector: 'HealthTech',     asset_type: 'stock', congress_flagged: false },
  { symbol: 'ILMN',  name: 'Illumina Inc.',            exchange: 'NASDAQ', sector: 'Genomics',       asset_type: 'stock', congress_flagged: false },
  { symbol: 'GILD',  name: 'Gilead Sciences',          exchange: 'NASDAQ', sector: 'Biotech',        asset_type: 'stock', congress_flagged: false },
  { symbol: 'BIIB',  name: 'Biogen Inc.',              exchange: 'NASDAQ', sector: 'Biotech',        asset_type: 'stock', congress_flagged: false },
  { symbol: 'REGN',  name: 'Regeneron Pharma',         exchange: 'NASDAQ', sector: 'Biotech',        asset_type: 'stock', congress_flagged: false },
  { symbol: 'VRTX',  name: 'Vertex Pharma',            exchange: 'NASDAQ', sector: 'Biotech',        asset_type: 'stock', congress_flagged: false },
  { symbol: 'MRNA',  name: 'Moderna Inc.',             exchange: 'NASDAQ', sector: 'Biotech',        asset_type: 'stock', congress_flagged: true  },
  { symbol: 'BNTX',  name: 'BioNTech SE',              exchange: 'NASDAQ', sector: 'Biotech',        asset_type: 'stock', congress_flagged: false },
  { symbol: 'SGEN',  name: 'Seagen Inc.',              exchange: 'NASDAQ', sector: 'Biotech',        asset_type: 'stock', congress_flagged: false },
  { symbol: 'ALNY',  name: 'Alnylam Pharma',           exchange: 'NASDAQ', sector: 'Biotech',        asset_type: 'stock', congress_flagged: false },
  { symbol: 'INCY',  name: 'Incyte Corp.',             exchange: 'NASDAQ', sector: 'Biotech',        asset_type: 'stock', congress_flagged: false },
  { symbol: 'EXAS',  name: 'Exact Sciences',           exchange: 'NASDAQ', sector: 'Diagnostics',    asset_type: 'stock', congress_flagged: false },
  { symbol: 'TDOC',  name: 'Teladoc Health',           exchange: 'NYSE',   sector: 'HealthTech',     asset_type: 'stock', congress_flagged: false },
  { symbol: 'PTON',  name: 'Peloton Interactive',      exchange: 'NASDAQ', sector: 'Fitness',        asset_type: 'stock', congress_flagged: false },
  { symbol: 'ETSY',  name: 'Etsy Inc.',                exchange: 'NASDAQ', sector: 'E-Commerce',     asset_type: 'stock', congress_flagged: false },
  { symbol: 'EBAY',  name: 'eBay Inc.',                exchange: 'NASDAQ', sector: 'E-Commerce',     asset_type: 'stock', congress_flagged: false },
  { symbol: 'BKNG',  name: 'Booking Holdings',         exchange: 'NASDAQ', sector: 'Travel',         asset_type: 'stock', congress_flagged: false },
  { symbol: 'EXPE',  name: 'Expedia Group',            exchange: 'NASDAQ', sector: 'Travel',         asset_type: 'stock', congress_flagged: false },
  { symbol: 'MAR',   name: 'Marriott Intl.',           exchange: 'NASDAQ', sector: 'Hotels',         asset_type: 'stock', congress_flagged: false },

  // ── NYSE ──────────────────────────────────────────────────────────────────
  { symbol: 'JPM',   name: 'JPMorgan Chase',           exchange: 'NYSE',   sector: 'Banking',        asset_type: 'stock', congress_flagged: true  },
  { symbol: 'BAC',   name: 'Bank of America',          exchange: 'NYSE',   sector: 'Banking',        asset_type: 'stock', congress_flagged: true  },
  { symbol: 'WFC',   name: 'Wells Fargo',              exchange: 'NYSE',   sector: 'Banking',        asset_type: 'stock', congress_flagged: false },
  { symbol: 'C',     name: 'Citigroup Inc.',           exchange: 'NYSE',   sector: 'Banking',        asset_type: 'stock', congress_flagged: false },
  { symbol: 'GS',    name: 'Goldman Sachs',            exchange: 'NYSE',   sector: 'Investment Banking', asset_type: 'stock', congress_flagged: true },
  { symbol: 'MS',    name: 'Morgan Stanley',           exchange: 'NYSE',   sector: 'Investment Banking', asset_type: 'stock', congress_flagged: false },
  { symbol: 'BX',    name: 'Blackstone Inc.',          exchange: 'NYSE',   sector: 'Private Equity', asset_type: 'stock', congress_flagged: false },
  { symbol: 'KKR',   name: 'KKR & Co.',               exchange: 'NYSE',   sector: 'Private Equity', asset_type: 'stock', congress_flagged: false },
  { symbol: 'APO',   name: 'Apollo Global Mgmt',       exchange: 'NYSE',   sector: 'Private Equity', asset_type: 'stock', congress_flagged: false },
  { symbol: 'BRK-B', name: 'Berkshire Hathaway B',     exchange: 'NYSE',   sector: 'Conglomerate',   asset_type: 'stock', congress_flagged: false },
  { symbol: 'V',     name: 'Visa Inc.',                exchange: 'NYSE',   sector: 'Payments',       asset_type: 'stock', congress_flagged: false },
  { symbol: 'MA',    name: 'Mastercard Inc.',          exchange: 'NYSE',   sector: 'Payments',       asset_type: 'stock', congress_flagged: false },
  { symbol: 'AXP',   name: 'American Express',         exchange: 'NYSE',   sector: 'Payments',       asset_type: 'stock', congress_flagged: false },
  { symbol: 'USB',   name: 'U.S. Bancorp',             exchange: 'NYSE',   sector: 'Banking',        asset_type: 'stock', congress_flagged: false },
  { symbol: 'PNC',   name: 'PNC Financial',            exchange: 'NYSE',   sector: 'Banking',        asset_type: 'stock', congress_flagged: false },
  { symbol: 'TFC',   name: 'Truist Financial',         exchange: 'NYSE',   sector: 'Banking',        asset_type: 'stock', congress_flagged: false },
  { symbol: 'COF',   name: 'Capital One Financial',    exchange: 'NYSE',   sector: 'Banking',        asset_type: 'stock', congress_flagged: false },
  { symbol: 'AIG',   name: 'American Intl Group',      exchange: 'NYSE',   sector: 'Insurance',      asset_type: 'stock', congress_flagged: false },
  { symbol: 'MET',   name: 'MetLife Inc.',             exchange: 'NYSE',   sector: 'Insurance',      asset_type: 'stock', congress_flagged: false },
  { symbol: 'PRU',   name: 'Prudential Financial',     exchange: 'NYSE',   sector: 'Insurance',      asset_type: 'stock', congress_flagged: false },
  { symbol: 'ALL',   name: 'Allstate Corp.',           exchange: 'NYSE',   sector: 'Insurance',      asset_type: 'stock', congress_flagged: false },
  { symbol: 'TRV',   name: 'Travelers Companies',      exchange: 'NYSE',   sector: 'Insurance',      asset_type: 'stock', congress_flagged: false },
  { symbol: 'CME',   name: 'CME Group',                exchange: 'NASDAQ', sector: 'Exchanges',      asset_type: 'stock', congress_flagged: false },
  { symbol: 'ICE',   name: 'Intercontinental Exchange',exchange: 'NYSE',   sector: 'Exchanges',      asset_type: 'stock', congress_flagged: false },
  { symbol: 'SCHW',  name: 'Charles Schwab',           exchange: 'NYSE',   sector: 'Brokerage',      asset_type: 'stock', congress_flagged: false },
  { symbol: 'WMT',   name: 'Walmart Inc.',             exchange: 'NYSE',   sector: 'Retail',         asset_type: 'stock', congress_flagged: false },
  { symbol: 'HD',    name: 'Home Depot',               exchange: 'NYSE',   sector: 'Home Improvement',asset_type: 'stock', congress_flagged: false },
  { symbol: 'LOW',   name: "Lowe's Companies",         exchange: 'NYSE',   sector: 'Home Improvement',asset_type: 'stock', congress_flagged: false },
  { symbol: 'TGT',   name: 'Target Corp.',             exchange: 'NYSE',   sector: 'Retail',         asset_type: 'stock', congress_flagged: false },
  { symbol: 'TJX',   name: 'TJX Companies',            exchange: 'NYSE',   sector: 'Retail',         asset_type: 'stock', congress_flagged: false },
  { symbol: 'COST',  name: 'Costco Wholesale',         exchange: 'NASDAQ', sector: 'Retail',         asset_type: 'stock', congress_flagged: false },
  { symbol: 'MCD',   name: "McDonald's Corp.",         exchange: 'NYSE',   sector: 'Restaurants',    asset_type: 'stock', congress_flagged: false },
  { symbol: 'SBUX',  name: 'Starbucks Corp.',          exchange: 'NASDAQ', sector: 'Restaurants',    asset_type: 'stock', congress_flagged: false },
  { symbol: 'YUM',   name: 'Yum! Brands',              exchange: 'NYSE',   sector: 'Restaurants',    asset_type: 'stock', congress_flagged: false },
  { symbol: 'DPZ',   name: "Domino's Pizza",           exchange: 'NYSE',   sector: 'Restaurants',    asset_type: 'stock', congress_flagged: false },
  { symbol: 'KO',    name: 'Coca-Cola Co.',            exchange: 'NYSE',   sector: 'Beverages',      asset_type: 'stock', congress_flagged: false },
  { symbol: 'PEP',   name: 'PepsiCo Inc.',             exchange: 'NASDAQ', sector: 'Beverages',      asset_type: 'stock', congress_flagged: false },
  { symbol: 'PG',    name: 'Procter & Gamble',         exchange: 'NYSE',   sector: 'Consumer Staples',asset_type: 'stock', congress_flagged: false },
  { symbol: 'CL',    name: 'Colgate-Palmolive',        exchange: 'NYSE',   sector: 'Consumer Staples',asset_type: 'stock', congress_flagged: false },
  { symbol: 'KMB',   name: 'Kimberly-Clark',           exchange: 'NYSE',   sector: 'Consumer Staples',asset_type: 'stock', congress_flagged: false },
  { symbol: 'NKE',   name: 'Nike Inc.',                exchange: 'NYSE',   sector: 'Apparel',        asset_type: 'stock', congress_flagged: false },
  { symbol: 'DIS',   name: 'Walt Disney Co.',          exchange: 'NYSE',   sector: 'Media',          asset_type: 'stock', congress_flagged: true  },
  { symbol: 'CMCSA', name: 'Comcast Corp.',            exchange: 'NASDAQ', sector: 'Media',          asset_type: 'stock', congress_flagged: false },
  { symbol: 'PARA',  name: 'Paramount Global',         exchange: 'NASDAQ', sector: 'Media',          asset_type: 'stock', congress_flagged: false },
  { symbol: 'WBD',   name: 'Warner Bros. Discovery',   exchange: 'NASDAQ', sector: 'Media',          asset_type: 'stock', congress_flagged: false },
  { symbol: 'JNJ',   name: 'Johnson & Johnson',        exchange: 'NYSE',   sector: 'Pharma',         asset_type: 'stock', congress_flagged: true  },
  { symbol: 'PFE',   name: 'Pfizer Inc.',              exchange: 'NYSE',   sector: 'Pharma',         asset_type: 'stock', congress_flagged: true  },
  { symbol: 'MRK',   name: 'Merck & Co.',              exchange: 'NYSE',   sector: 'Pharma',         asset_type: 'stock', congress_flagged: false },
  { symbol: 'ABBV',  name: 'AbbVie Inc.',              exchange: 'NYSE',   sector: 'Pharma',         asset_type: 'stock', congress_flagged: false },
  { symbol: 'LLY',   name: 'Eli Lilly & Co.',          exchange: 'NYSE',   sector: 'Pharma',         asset_type: 'stock', congress_flagged: true  },
  { symbol: 'BMY',   name: 'Bristol-Myers Squibb',     exchange: 'NYSE',   sector: 'Pharma',         asset_type: 'stock', congress_flagged: false },
  { symbol: 'CVS',   name: 'CVS Health Corp.',         exchange: 'NYSE',   sector: 'Healthcare',     asset_type: 'stock', congress_flagged: false },
  { symbol: 'UNH',   name: 'UnitedHealth Group',       exchange: 'NYSE',   sector: 'Health Insurance',asset_type: 'stock', congress_flagged: false },
  { symbol: 'HUM',   name: 'Humana Inc.',              exchange: 'NYSE',   sector: 'Health Insurance',asset_type: 'stock', congress_flagged: false },
  { symbol: 'CI',    name: 'Cigna Group',              exchange: 'NYSE',   sector: 'Health Insurance',asset_type: 'stock', congress_flagged: false },
  { symbol: 'HCA',   name: 'HCA Healthcare',           exchange: 'NYSE',   sector: 'Healthcare',     asset_type: 'stock', congress_flagged: false },
  { symbol: 'TMO',   name: 'Thermo Fisher Scientific', exchange: 'NYSE',   sector: 'Life Sciences',  asset_type: 'stock', congress_flagged: false },
  { symbol: 'DHR',   name: 'Danaher Corp.',            exchange: 'NYSE',   sector: 'Life Sciences',  asset_type: 'stock', congress_flagged: false },
  { symbol: 'ABT',   name: 'Abbott Laboratories',      exchange: 'NYSE',   sector: 'Medical Devices',asset_type: 'stock', congress_flagged: false },
  { symbol: 'MDT',   name: 'Medtronic plc',            exchange: 'NYSE',   sector: 'Medical Devices',asset_type: 'stock', congress_flagged: false },
  { symbol: 'SYK',   name: 'Stryker Corp.',            exchange: 'NYSE',   sector: 'Medical Devices',asset_type: 'stock', congress_flagged: false },
  { symbol: 'XOM',   name: 'Exxon Mobil',              exchange: 'NYSE',   sector: 'Energy',         asset_type: 'stock', congress_flagged: false },
  { symbol: 'CVX',   name: 'Chevron Corp.',            exchange: 'NYSE',   sector: 'Energy',         asset_type: 'stock', congress_flagged: false },
  { symbol: 'COP',   name: 'ConocoPhillips',           exchange: 'NYSE',   sector: 'Energy',         asset_type: 'stock', congress_flagged: false },
  { symbol: 'SLB',   name: 'SLB (Schlumberger)',       exchange: 'NYSE',   sector: 'Energy Services',asset_type: 'stock', congress_flagged: false },
  { symbol: 'HAL',   name: 'Halliburton Co.',          exchange: 'NYSE',   sector: 'Energy Services',asset_type: 'stock', congress_flagged: false },
  { symbol: 'OXY',   name: 'Occidental Petroleum',     exchange: 'NYSE',   sector: 'Energy',         asset_type: 'stock', congress_flagged: false },
  { symbol: 'MPC',   name: 'Marathon Petroleum',       exchange: 'NYSE',   sector: 'Energy',         asset_type: 'stock', congress_flagged: false },
  { symbol: 'VLO',   name: 'Valero Energy',            exchange: 'NYSE',   sector: 'Energy',         asset_type: 'stock', congress_flagged: false },
  { symbol: 'PSX',   name: 'Phillips 66',              exchange: 'NYSE',   sector: 'Energy',         asset_type: 'stock', congress_flagged: false },
  { symbol: 'NEE',   name: 'NextEra Energy',           exchange: 'NYSE',   sector: 'Utilities',      asset_type: 'stock', congress_flagged: false },
  { symbol: 'DUK',   name: 'Duke Energy',              exchange: 'NYSE',   sector: 'Utilities',      asset_type: 'stock', congress_flagged: false },
  { symbol: 'SO',    name: 'Southern Company',         exchange: 'NYSE',   sector: 'Utilities',      asset_type: 'stock', congress_flagged: false },
  { symbol: 'AEP',   name: 'American Electric Power',  exchange: 'NASDAQ', sector: 'Utilities',      asset_type: 'stock', congress_flagged: false },
  { symbol: 'D',     name: 'Dominion Energy',          exchange: 'NYSE',   sector: 'Utilities',      asset_type: 'stock', congress_flagged: false },
  { symbol: 'EXC',   name: 'Exelon Corp.',             exchange: 'NASDAQ', sector: 'Utilities',      asset_type: 'stock', congress_flagged: false },
  { symbol: 'BA',    name: 'Boeing Co.',               exchange: 'NYSE',   sector: 'Aerospace',      asset_type: 'stock', congress_flagged: false },
  { symbol: 'RTX',   name: 'RTX Corp. (Raytheon)',     exchange: 'NYSE',   sector: 'Defense',        asset_type: 'stock', congress_flagged: true  },
  { symbol: 'LMT',   name: 'Lockheed Martin',          exchange: 'NYSE',   sector: 'Defense',        asset_type: 'stock', congress_flagged: true  },
  { symbol: 'NOC',   name: 'Northrop Grumman',         exchange: 'NYSE',   sector: 'Defense',        asset_type: 'stock', congress_flagged: true  },
  { symbol: 'GD',    name: 'General Dynamics',         exchange: 'NYSE',   sector: 'Defense',        asset_type: 'stock', congress_flagged: true  },
  { symbol: 'HII',   name: 'Huntington Ingalls',       exchange: 'NYSE',   sector: 'Defense',        asset_type: 'stock', congress_flagged: false },
  { symbol: 'CAT',   name: 'Caterpillar Inc.',         exchange: 'NYSE',   sector: 'Machinery',      asset_type: 'stock', congress_flagged: false },
  { symbol: 'DE',    name: 'Deere & Company',          exchange: 'NYSE',   sector: 'Machinery',      asset_type: 'stock', congress_flagged: false },
  { symbol: 'HON',   name: 'Honeywell Intl.',          exchange: 'NASDAQ', sector: 'Industrials',    asset_type: 'stock', congress_flagged: false },
  { symbol: 'MMM',   name: '3M Company',               exchange: 'NYSE',   sector: 'Industrials',    asset_type: 'stock', congress_flagged: false },
  { symbol: 'GE',    name: 'GE Aerospace',             exchange: 'NYSE',   sector: 'Industrials',    asset_type: 'stock', congress_flagged: false },
  { symbol: 'EMR',   name: 'Emerson Electric',         exchange: 'NYSE',   sector: 'Industrials',    asset_type: 'stock', congress_flagged: false },
  { symbol: 'ROK',   name: 'Rockwell Automation',      exchange: 'NYSE',   sector: 'Automation',     asset_type: 'stock', congress_flagged: false },
  { symbol: 'ETN',   name: 'Eaton Corp.',              exchange: 'NYSE',   sector: 'Industrials',    asset_type: 'stock', congress_flagged: false },
  { symbol: 'URI',   name: 'United Rentals',           exchange: 'NYSE',   sector: 'Equipment Rental',asset_type: 'stock', congress_flagged: false },
  { symbol: 'UPS',   name: 'United Parcel Service',    exchange: 'NYSE',   sector: 'Logistics',      asset_type: 'stock', congress_flagged: false },
  { symbol: 'FDX',   name: 'FedEx Corp.',              exchange: 'NYSE',   sector: 'Logistics',      asset_type: 'stock', congress_flagged: false },
  { symbol: 'F',     name: 'Ford Motor Co.',           exchange: 'NYSE',   sector: 'Automotive',     asset_type: 'stock', congress_flagged: false },
  { symbol: 'GM',    name: 'General Motors',           exchange: 'NYSE',   sector: 'Automotive',     asset_type: 'stock', congress_flagged: false },
  { symbol: 'T',     name: 'AT&T Inc.',                exchange: 'NYSE',   sector: 'Telecom',        asset_type: 'stock', congress_flagged: false },
  { symbol: 'VZ',    name: 'Verizon Communications',   exchange: 'NYSE',   sector: 'Telecom',        asset_type: 'stock', congress_flagged: false },
  { symbol: 'TMUS',  name: 'T-Mobile US',              exchange: 'NASDAQ', sector: 'Telecom',        asset_type: 'stock', congress_flagged: false },
  { symbol: 'AMT',   name: 'American Tower Corp.',     exchange: 'NYSE',   sector: 'Cell Towers',    asset_type: 'stock', congress_flagged: false },
  { symbol: 'CCI',   name: 'Crown Castle Inc.',        exchange: 'NYSE',   sector: 'Cell Towers',    asset_type: 'stock', congress_flagged: false },
  { symbol: 'PLD',   name: 'Prologis Inc.',            exchange: 'NYSE',   sector: 'REIT',           asset_type: 'stock', congress_flagged: false },
  { symbol: 'EQIX',  name: 'Equinix Inc.',             exchange: 'NASDAQ', sector: 'Data Center REIT',asset_type: 'stock', congress_flagged: false },
  { symbol: 'DLR',   name: 'Digital Realty Trust',     exchange: 'NYSE',   sector: 'Data Center REIT',asset_type: 'stock', congress_flagged: false },
  { symbol: 'SPG',   name: 'Simon Property Group',     exchange: 'NYSE',   sector: 'REIT',           asset_type: 'stock', congress_flagged: false },
  { symbol: 'O',     name: 'Realty Income Corp.',      exchange: 'NYSE',   sector: 'REIT',           asset_type: 'stock', congress_flagged: false },

  // ── ETFs ──────────────────────────────────────────────────────────────────
  { symbol: 'SPY',   name: 'SPDR S&P 500 ETF',         exchange: 'NYSE',   sector: 'Index ETF',      asset_type: 'etf',   congress_flagged: false },
  { symbol: 'QQQ',   name: 'Invesco QQQ Trust',        exchange: 'NASDAQ', sector: 'Index ETF',      asset_type: 'etf',   congress_flagged: false },
  { symbol: 'IWM',   name: 'iShares Russell 2000',     exchange: 'NYSE',   sector: 'Index ETF',      asset_type: 'etf',   congress_flagged: false },
  { symbol: 'VTI',   name: 'Vanguard Total Market',    exchange: 'NYSE',   sector: 'Index ETF',      asset_type: 'etf',   congress_flagged: false },
  { symbol: 'DIA',   name: 'SPDR Dow Jones ETF',       exchange: 'NYSE',   sector: 'Index ETF',      asset_type: 'etf',   congress_flagged: false },
  { symbol: 'GLD',   name: 'SPDR Gold Shares',         exchange: 'NYSE',   sector: 'Commodities ETF',asset_type: 'etf',   congress_flagged: false },
  { symbol: 'SLV',   name: 'iShares Silver Trust',     exchange: 'NYSE',   sector: 'Commodities ETF',asset_type: 'etf',   congress_flagged: false },
  { symbol: 'USO',   name: 'US Oil Fund',              exchange: 'NYSE',   sector: 'Commodities ETF',asset_type: 'etf',   congress_flagged: false },
  { symbol: 'ARKK',  name: 'ARK Innovation ETF',       exchange: 'NYSE',   sector: 'Innovation ETF', asset_type: 'etf',   congress_flagged: false },
  { symbol: 'SOXL',  name: 'Direxion Semis 3x Bull',   exchange: 'NYSE',   sector: 'Leveraged ETF',  asset_type: 'etf',   congress_flagged: false },
  { symbol: 'TQQQ',  name: 'ProShares UltraPro QQQ',   exchange: 'NASDAQ', sector: 'Leveraged ETF',  asset_type: 'etf',   congress_flagged: false },
  { symbol: 'SPXL',  name: 'Direxion S&P 500 3x Bull', exchange: 'NYSE',   sector: 'Leveraged ETF',  asset_type: 'etf',   congress_flagged: false },
  { symbol: 'UVXY',  name: 'ProShares Ultra VIX',      exchange: 'NASDAQ', sector: 'Volatility ETF', asset_type: 'etf',   congress_flagged: false },
  { symbol: 'LABU',  name: 'Direxion Biotech 3x Bull', exchange: 'NYSE',   sector: 'Leveraged ETF',  asset_type: 'etf',   congress_flagged: false },

  // ── CRYPTO ──────────────────────────────────────────────────────────────────
  { symbol: 'BTC-USD',  name: 'Bitcoin',           exchange: 'CRYPTO', sector: 'L1',       asset_type: 'crypto', congress_flagged: false },
  { symbol: 'ETH-USD',  name: 'Ethereum',          exchange: 'CRYPTO', sector: 'L1',       asset_type: 'crypto', congress_flagged: false },
  { symbol: 'SOL-USD',  name: 'Solana',            exchange: 'CRYPTO', sector: 'L1',       asset_type: 'crypto', congress_flagged: false },
  { symbol: 'BNB-USD',  name: 'BNB',               exchange: 'CRYPTO', sector: 'L1',       asset_type: 'crypto', congress_flagged: false },
  { symbol: 'XRP-USD',  name: 'XRP (Ripple)',      exchange: 'CRYPTO', sector: 'Payments', asset_type: 'crypto', congress_flagged: false },
  { symbol: 'ADA-USD',  name: 'Cardano',           exchange: 'CRYPTO', sector: 'L1',       asset_type: 'crypto', congress_flagged: false },
  { symbol: 'AVAX-USD', name: 'Avalanche',         exchange: 'CRYPTO', sector: 'L1',       asset_type: 'crypto', congress_flagged: false },
  { symbol: 'DOGE-USD', name: 'Dogecoin',          exchange: 'CRYPTO', sector: 'Meme',     asset_type: 'crypto', congress_flagged: false },
  { symbol: 'DOT-USD',  name: 'Polkadot',          exchange: 'CRYPTO', sector: 'L0',       asset_type: 'crypto', congress_flagged: false },
  { symbol: 'MATIC-USD',name: 'Polygon (MATIC)',   exchange: 'CRYPTO', sector: 'L2',       asset_type: 'crypto', congress_flagged: false },
  { symbol: 'LINK-USD', name: 'Chainlink',         exchange: 'CRYPTO', sector: 'Oracle',   asset_type: 'crypto', congress_flagged: false },
  { symbol: 'UNI-USD',  name: 'Uniswap',           exchange: 'CRYPTO', sector: 'DeFi DEX', asset_type: 'crypto', congress_flagged: false },
  { symbol: 'AAVE-USD', name: 'Aave',              exchange: 'CRYPTO', sector: 'DeFi Lending', asset_type: 'crypto', congress_flagged: false },
  { symbol: 'ATOM-USD', name: 'Cosmos',            exchange: 'CRYPTO', sector: 'L0',       asset_type: 'crypto', congress_flagged: false },
  { symbol: 'LTC-USD',  name: 'Litecoin',          exchange: 'CRYPTO', sector: 'Payments', asset_type: 'crypto', congress_flagged: false },
  { symbol: 'BCH-USD',  name: 'Bitcoin Cash',      exchange: 'CRYPTO', sector: 'Payments', asset_type: 'crypto', congress_flagged: false },
  { symbol: 'ETC-USD',  name: 'Ethereum Classic',  exchange: 'CRYPTO', sector: 'L1',       asset_type: 'crypto', congress_flagged: false },
  { symbol: 'FIL-USD',  name: 'Filecoin',          exchange: 'CRYPTO', sector: 'Storage',  asset_type: 'crypto', congress_flagged: false },
  { symbol: 'ALGO-USD', name: 'Algorand',          exchange: 'CRYPTO', sector: 'L1',       asset_type: 'crypto', congress_flagged: false },
  { symbol: 'NEAR-USD', name: 'NEAR Protocol',     exchange: 'CRYPTO', sector: 'L1',       asset_type: 'crypto', congress_flagged: false },
  { symbol: 'APT-USD',  name: 'Aptos',             exchange: 'CRYPTO', sector: 'L1',       asset_type: 'crypto', congress_flagged: false },
  { symbol: 'SUI-USD',  name: 'Sui',               exchange: 'CRYPTO', sector: 'L1',       asset_type: 'crypto', congress_flagged: false },
  { symbol: 'SEI-USD',  name: 'Sei Network',       exchange: 'CRYPTO', sector: 'L1',       asset_type: 'crypto', congress_flagged: false },
  { symbol: 'TIA-USD',  name: 'Celestia',          exchange: 'CRYPTO', sector: 'Modular',  asset_type: 'crypto', congress_flagged: false },
  { symbol: 'ARB-USD',  name: 'Arbitrum',          exchange: 'CRYPTO', sector: 'L2',       asset_type: 'crypto', congress_flagged: false },
  { symbol: 'OP-USD',   name: 'Optimism',          exchange: 'CRYPTO', sector: 'L2',       asset_type: 'crypto', congress_flagged: false },
  { symbol: 'STRK-USD', name: 'Starknet',          exchange: 'CRYPTO', sector: 'L2',       asset_type: 'crypto', congress_flagged: false },
  { symbol: 'ZK-USD',   name: 'ZKsync',            exchange: 'CRYPTO', sector: 'L2',       asset_type: 'crypto', congress_flagged: false },
  { symbol: 'SHIB-USD', name: 'Shiba Inu',         exchange: 'CRYPTO', sector: 'Meme',     asset_type: 'crypto', congress_flagged: false },
  { symbol: 'PEPE-USD', name: 'Pepe',              exchange: 'CRYPTO', sector: 'Meme',     asset_type: 'crypto', congress_flagged: false },
  { symbol: 'WIF-USD',  name: 'dogwifhat',         exchange: 'CRYPTO', sector: 'Meme',     asset_type: 'crypto', congress_flagged: false },
  { symbol: 'BONK-USD', name: 'Bonk',              exchange: 'CRYPTO', sector: 'Meme',     asset_type: 'crypto', congress_flagged: false },
  { symbol: 'JUP-USD',  name: 'Jupiter',           exchange: 'CRYPTO', sector: 'DeFi DEX', asset_type: 'crypto', congress_flagged: false },
  { symbol: 'PYTH-USD', name: 'Pyth Network',      exchange: 'CRYPTO', sector: 'Oracle',   asset_type: 'crypto', congress_flagged: false },
  { symbol: 'W-USD',    name: 'Wormhole',          exchange: 'CRYPTO', sector: 'Bridge',   asset_type: 'crypto', congress_flagged: false },
  { symbol: 'RENDER-USD',name:'Render Network',    exchange: 'CRYPTO', sector: 'AI/GPU',   asset_type: 'crypto', congress_flagged: false },
  { symbol: 'FET-USD',  name: 'Fetch.ai',          exchange: 'CRYPTO', sector: 'AI',       asset_type: 'crypto', congress_flagged: false },
  { symbol: 'OCEAN-USD',name: 'Ocean Protocol',    exchange: 'CRYPTO', sector: 'AI/Data',  asset_type: 'crypto', congress_flagged: false },
  { symbol: 'INJ-USD',  name: 'Injective',         exchange: 'CRYPTO', sector: 'DeFi L1',  asset_type: 'crypto', congress_flagged: false },
  { symbol: 'GMX-USD',  name: 'GMX',               exchange: 'CRYPTO', sector: 'DeFi Perps',asset_type: 'crypto', congress_flagged: false },
  { symbol: 'PENDLE-USD',name:'Pendle Finance',    exchange: 'CRYPTO', sector: 'DeFi Yield',asset_type: 'crypto', congress_flagged: false },
  { symbol: 'ENA-USD',  name: 'Ethena',            exchange: 'CRYPTO', sector: 'Stablecoin',asset_type: 'crypto', congress_flagged: false },
  { symbol: 'ETHFI-USD',name: 'Ether.fi',          exchange: 'CRYPTO', sector: 'Restaking',asset_type: 'crypto', congress_flagged: false },
  { symbol: 'EIGEN-USD',name: 'EigenLayer',        exchange: 'CRYPTO', sector: 'Restaking',asset_type: 'crypto', congress_flagged: false },
  { symbol: 'MKR-USD',  name: 'Maker (Sky)',       exchange: 'CRYPTO', sector: 'DeFi DAO',  asset_type: 'crypto', congress_flagged: false },
  { symbol: 'CRV-USD',  name: 'Curve DAO',         exchange: 'CRYPTO', sector: 'DeFi DEX', asset_type: 'crypto', congress_flagged: false },
  { symbol: 'SNX-USD',  name: 'Synthetix',         exchange: 'CRYPTO', sector: 'DeFi Synths',asset_type: 'crypto', congress_flagged: false },
  { symbol: 'LDO-USD',  name: 'Lido DAO',          exchange: 'CRYPTO', sector: 'Liquid Staking',asset_type: 'crypto', congress_flagged: false },
  { symbol: 'RPL-USD',  name: 'Rocket Pool',       exchange: 'CRYPTO', sector: 'Liquid Staking',asset_type: 'crypto', congress_flagged: false },
  { symbol: 'GRT-USD',  name: 'The Graph',         exchange: 'CRYPTO', sector: 'Indexing', asset_type: 'crypto', congress_flagged: false },
  { symbol: 'SAND-USD', name: 'The Sandbox',       exchange: 'CRYPTO', sector: 'Metaverse',asset_type: 'crypto', congress_flagged: false },
  { symbol: 'MANA-USD', name: 'Decentraland',      exchange: 'CRYPTO', sector: 'Metaverse',asset_type: 'crypto', congress_flagged: false },
  { symbol: 'AXS-USD',  name: 'Axie Infinity',     exchange: 'CRYPTO', sector: 'Gaming',   asset_type: 'crypto', congress_flagged: false },
  { symbol: 'IMX-USD',  name: 'Immutable X',       exchange: 'CRYPTO', sector: 'Gaming L2',asset_type: 'crypto', congress_flagged: false },
  { symbol: 'XLM-USD',  name: 'Stellar',           exchange: 'CRYPTO', sector: 'Payments', asset_type: 'crypto', congress_flagged: false },
  { symbol: 'VET-USD',  name: 'VeChain',           exchange: 'CRYPTO', sector: 'Supply Chain',asset_type: 'crypto', congress_flagged: false },
  { symbol: 'ICP-USD',  name: 'Internet Computer', exchange: 'CRYPTO', sector: 'L1',       asset_type: 'crypto', congress_flagged: false },
  { symbol: 'HBAR-USD', name: 'Hedera Hashgraph',  exchange: 'CRYPTO', sector: 'L1',       asset_type: 'crypto', congress_flagged: false },
  { symbol: 'QNT-USD',  name: 'Quant Network',     exchange: 'CRYPTO', sector: 'Interop',  asset_type: 'crypto', congress_flagged: false },
  { symbol: 'FLOW-USD', name: 'Flow Blockchain',   exchange: 'CRYPTO', sector: 'NFT L1',   asset_type: 'crypto', congress_flagged: false },
  { symbol: 'THETA-USD',name: 'Theta Network',     exchange: 'CRYPTO', sector: 'Media',    asset_type: 'crypto', congress_flagged: false },

  // ── Space & Aerospace ─────────────────────────────────────────────────────
  // SpaceX IPO'd on NASDAQ June 12, 2026 under ticker SPCX ($135 IPO → $161 close, $2T+ mkt cap)
  { symbol: 'RKLB',  name: 'Rocket Lab USA',        exchange: 'NASDAQ', sector: 'Space',          asset_type: 'stock', congress_flagged: false },
  { symbol: 'ASTS',  name: 'AST SpaceMobile',       exchange: 'NASDAQ', sector: 'Space Telecom',  asset_type: 'stock', congress_flagged: false },
  { symbol: 'SPCE',  name: 'Virgin Galactic',       exchange: 'NYSE',   sector: 'Space Tourism',  asset_type: 'stock', congress_flagged: false },
  { symbol: 'MNTS',  name: 'Momentus Inc.',         exchange: 'NASDAQ', sector: 'Space Services',  asset_type: 'stock', congress_flagged: false },
  { symbol: 'ASTR',  name: 'Astra Space Inc.',      exchange: 'NASDAQ', sector: 'Space Launch',   asset_type: 'stock', congress_flagged: false },
  { symbol: 'PL',    name: 'Planet Labs PBC',       exchange: 'NYSE',   sector: 'Satellite Imaging',asset_type: 'stock', congress_flagged: false },
  { symbol: 'BKSY',  name: 'BlackSky Technology',   exchange: 'NYSE',   sector: 'Satellite Imaging',asset_type: 'stock', congress_flagged: false },
  { symbol: 'SPIR',  name: 'Spire Global Inc.',     exchange: 'NYSE',   sector: 'Satellite Data',  asset_type: 'stock', congress_flagged: false },
  { symbol: 'SATL',  name: 'Satellogic Inc.',       exchange: 'NASDAQ', sector: 'Satellite Imaging',asset_type: 'stock', congress_flagged: false },
  { symbol: 'KTOS',  name: 'Kratos Defense',        exchange: 'NASDAQ', sector: 'Defense/Space',  asset_type: 'stock', congress_flagged: false },
  { symbol: 'AJRD',  name: 'Aerojet Rocketdyne',    exchange: 'NYSE',   sector: 'Space Propulsion',asset_type: 'stock', congress_flagged: false },
  { symbol: 'MAXR',  name: 'Maxar Technologies',    exchange: 'NYSE',   sector: 'Satellite/Space', asset_type: 'stock', congress_flagged: false },
  { symbol: 'GSAT',  name: 'Globalstar Inc.',       exchange: 'NYSE',   sector: 'Satellite Comms', asset_type: 'stock', congress_flagged: false },
  { symbol: 'VSAT',  name: 'ViaSat Inc.',           exchange: 'NASDAQ', sector: 'Satellite Comms', asset_type: 'stock', congress_flagged: false },
  { symbol: 'LSXMA', name: 'Liberty Media (Sirius)',exchange: 'NASDAQ', sector: 'Satellite Media',  asset_type: 'stock', congress_flagged: false },
  { symbol: 'SIRI',  name: 'SiriusXM Holdings',     exchange: 'NASDAQ', sector: 'Satellite Radio', asset_type: 'stock', congress_flagged: false },
  { symbol: 'TDY',   name: 'Teledyne Technologies', exchange: 'NYSE',   sector: 'Aerospace Tech',  asset_type: 'stock', congress_flagged: false },
  { symbol: 'HXL',   name: 'Hexcel Corp.',          exchange: 'NYSE',   sector: 'Aerospace Materials',asset_type: 'stock', congress_flagged: false },
  { symbol: 'CW',    name: 'Curtiss-Wright Corp.',  exchange: 'NYSE',   sector: 'Aerospace Defense',asset_type: 'stock', congress_flagged: false },
  { symbol: 'VSEC',  name: 'VSE Corp.',             exchange: 'NASDAQ', sector: 'Aerospace Services',asset_type: 'stock', congress_flagged: false },
  { symbol: 'GENC',  name: 'Gencor Industries',     exchange: 'NASDAQ', sector: 'Industrials',     asset_type: 'stock', congress_flagged: false },
  // SpaceX IPO — NASDAQ June 12, 2026 (ticker SPCX; previously Procure Space ETF ticker, now SpaceX)
  { symbol: 'SPCX',  name: 'SpaceX (Space Exploration Technologies)', exchange: 'NASDAQ', sector: 'Space/AI', asset_type: 'stock', congress_flagged: false },
  // Space ETFs
  { symbol: 'UFO',   name: 'Procure Space ETF (UFO)',exchange: 'NYSE',   sector: 'Space ETF',       asset_type: 'etf',   congress_flagged: false },
  { symbol: 'ROKT',  name: 'SPDR S&P Kensho Final Frontiers ETF', exchange: 'NYSE', sector: 'Space ETF', asset_type: 'etf', congress_flagged: false },
  { symbol: 'ITA',   name: 'iShares US Aerospace & Defense ETF', exchange: 'BATS', sector: 'Aerospace ETF', asset_type: 'etf', congress_flagged: false },
  { symbol: 'PPA',   name: 'Invesco Aerospace & Defense ETF', exchange: 'NASDAQ', sector: 'Aerospace ETF', asset_type: 'etf', congress_flagged: false },
  { symbol: 'XAR',   name: 'SPDR S&P Aerospace & Defense ETF', exchange: 'NYSE', sector: 'Aerospace ETF', asset_type: 'etf', congress_flagged: false },

  // ── AI / Data Center expansion ────────────────────────────────────────────
  { symbol: 'DELL',  name: 'Dell Technologies',     exchange: 'NYSE',   sector: 'Technology',     asset_type: 'stock', congress_flagged: false },
  { symbol: 'HPE',   name: 'Hewlett Packard Enterprise', exchange: 'NYSE', sector: 'Technology',  asset_type: 'stock', congress_flagged: false },
  { symbol: 'NTAP',  name: 'NetApp Inc.',           exchange: 'NASDAQ', sector: 'Storage/Cloud',  asset_type: 'stock', congress_flagged: false },
  { symbol: 'PSTG',  name: 'Pure Storage Inc.',     exchange: 'NYSE',   sector: 'Storage',        asset_type: 'stock', congress_flagged: false },
  { symbol: 'VRT',   name: 'Vertiv Holdings',       exchange: 'NYSE',   sector: 'Data Center Infra',asset_type: 'stock', congress_flagged: false },
  { symbol: 'EQIX',  name: 'Equinix Inc.',          exchange: 'NASDAQ', sector: 'Data Center REIT',asset_type: 'stock', congress_flagged: false },
  { symbol: 'CDNS',  name: 'Cadence Design Systems',exchange: 'NASDAQ', sector: 'EDA Software',   asset_type: 'stock', congress_flagged: false },
  { symbol: 'SNPS',  name: 'Synopsys Inc.',         exchange: 'NASDAQ', sector: 'EDA Software',   asset_type: 'stock', congress_flagged: false },
  { symbol: 'MPWR',  name: 'Monolithic Power Sys.', exchange: 'NASDAQ', sector: 'Semiconductors',  asset_type: 'stock', congress_flagged: false },

  // ── Nuclear Energy ────────────────────────────────────────────────────────
  { symbol: 'CCJ',   name: 'Cameco Corp.',          exchange: 'NYSE',   sector: 'Uranium',        asset_type: 'stock', congress_flagged: false },
  { symbol: 'UEC',   name: 'Uranium Energy Corp.',  exchange: 'NYSE',   sector: 'Uranium',        asset_type: 'stock', congress_flagged: false },
  { symbol: 'NXE',   name: 'NexGen Energy',         exchange: 'NYSE',   sector: 'Uranium',        asset_type: 'stock', congress_flagged: false },
  { symbol: 'SMR',   name: 'NuScale Power',         exchange: 'NYSE',   sector: 'Nuclear SMR',    asset_type: 'stock', congress_flagged: false },
  { symbol: 'OKLO',  name: 'Oklo Inc.',             exchange: 'NYSE',   sector: 'Nuclear SMR',    asset_type: 'stock', congress_flagged: false },
  { symbol: 'CEG',   name: 'Constellation Energy',  exchange: 'NASDAQ', sector: 'Nuclear Power',  asset_type: 'stock', congress_flagged: false },
  { symbol: 'VST',   name: 'Vistra Corp.',          exchange: 'NYSE',   sector: 'Power/Nuclear',  asset_type: 'stock', congress_flagged: false },
  { symbol: 'URNM',  name: 'Sprott Uranium Miners ETF', exchange: 'NYSE', sector: 'Uranium ETF',  asset_type: 'etf',   congress_flagged: false },
  { symbol: 'URA',   name: 'Global X Uranium ETF',  exchange: 'NYSE',   sector: 'Uranium ETF',    asset_type: 'etf',   congress_flagged: false },

  // ── Biotech expansion ─────────────────────────────────────────────────────
  { symbol: 'NVAX',  name: 'Novavax Inc.',          exchange: 'NASDAQ', sector: 'Biotech',        asset_type: 'stock', congress_flagged: false },
  { symbol: 'ARWR',  name: 'Arrowhead Pharma',      exchange: 'NASDAQ', sector: 'Biotech',        asset_type: 'stock', congress_flagged: false },
  { symbol: 'BEAM',  name: 'Beam Therapeutics',     exchange: 'NASDAQ', sector: 'Gene Editing',   asset_type: 'stock', congress_flagged: false },
  { symbol: 'EDIT',  name: 'Editas Medicine',       exchange: 'NASDAQ', sector: 'Gene Editing',   asset_type: 'stock', congress_flagged: false },
  { symbol: 'CRSP',  name: 'CRISPR Therapeutics',   exchange: 'NASDAQ', sector: 'Gene Editing',   asset_type: 'stock', congress_flagged: false },
  { symbol: 'NTLA',  name: 'Intellia Therapeutics', exchange: 'NASDAQ', sector: 'Gene Editing',   asset_type: 'stock', congress_flagged: false },

  // ── Additional Crypto ─────────────────────────────────────────────────────
  { symbol: 'ONDO-USD', name: 'Ondo Finance',       exchange: 'CRYPTO', sector: 'RWA',           asset_type: 'crypto', congress_flagged: false },
  { symbol: 'XLM-USD',  name: 'Stellar',            exchange: 'CRYPTO', sector: 'Payments',      asset_type: 'crypto', congress_flagged: false },
  { symbol: 'ENA-USD',  name: 'Ethena',             exchange: 'CRYPTO', sector: 'Stablecoin',    asset_type: 'crypto', congress_flagged: false },
  { symbol: 'TON-USD',  name: 'Toncoin',            exchange: 'CRYPTO', sector: 'L1',            asset_type: 'crypto', congress_flagged: false },
  { symbol: 'TAO-USD',  name: 'Bittensor',          exchange: 'CRYPTO', sector: 'AI',            asset_type: 'crypto', congress_flagged: false },
  { symbol: 'SUI-USD',  name: 'Sui',                exchange: 'CRYPTO', sector: 'L1',            asset_type: 'crypto', congress_flagged: false },
  { symbol: 'SEI-USD',  name: 'Sei Network',        exchange: 'CRYPTO', sector: 'L1',            asset_type: 'crypto', congress_flagged: false },
  { symbol: 'APT-USD',  name: 'Aptos',              exchange: 'CRYPTO', sector: 'L1',            asset_type: 'crypto', congress_flagged: false },
];

export const EXCHANGES = ['All', 'NASDAQ', 'NYSE', 'CRYPTO', 'ETF'];