// Fixed asset universe for the Dashboard AI insights scan
// Covers: S&P 500 blue chips, Nasdaq 100, Dow Jones 30, Space/Aerospace, and CLARITY Act crypto
// SpaceX (SPCX) IPO'd on NASDAQ June 12, 2026 — $2T+ market cap

export const DASHBOARD_ASSETS = [
  // ── Dow Jones 30 ─────────────────────────────────────────────────────────
  { symbol: 'AAPL',  name: 'Apple Inc.',           exchange: 'NASDAQ', sector: 'Technology',       index: 'Dow' },
  { symbol: 'MSFT',  name: 'Microsoft Corp.',       exchange: 'NASDAQ', sector: 'Technology',       index: 'Dow' },
  { symbol: 'GS',    name: 'Goldman Sachs',         exchange: 'NYSE',   sector: 'Financials',       index: 'Dow' },
  { symbol: 'UNH',   name: 'UnitedHealth Group',    exchange: 'NYSE',   sector: 'Healthcare',       index: 'Dow' },
  { symbol: 'HD',    name: 'Home Depot',            exchange: 'NYSE',   sector: 'Consumer',         index: 'Dow' },
  { symbol: 'CAT',   name: 'Caterpillar Inc.',      exchange: 'NYSE',   sector: 'Industrials',      index: 'Dow' },
  { symbol: 'BA',    name: 'Boeing Co.',            exchange: 'NYSE',   sector: 'Aerospace',        index: 'Dow' },
  { symbol: 'IBM',   name: 'IBM Corp.',             exchange: 'NYSE',   sector: 'Technology',       index: 'Dow' },
  { symbol: 'AXP',   name: 'American Express',      exchange: 'NYSE',   sector: 'Financials',       index: 'Dow' },
  { symbol: 'JNJ',   name: 'Johnson & Johnson',     exchange: 'NYSE',   sector: 'Healthcare',       index: 'Dow' },
  { symbol: 'MCD',   name: "McDonald's Corp.",      exchange: 'NYSE',   sector: 'Consumer',         index: 'Dow' },
  { symbol: 'WMT',   name: 'Walmart Inc.',          exchange: 'NYSE',   sector: 'Retail',           index: 'Dow' },
  { symbol: 'CVX',   name: 'Chevron Corp.',         exchange: 'NYSE',   sector: 'Energy',           index: 'Dow' },
  { symbol: 'V',     name: 'Visa Inc.',             exchange: 'NYSE',   sector: 'Financials',       index: 'Dow' },
  { symbol: 'JPM',   name: 'JPMorgan Chase',        exchange: 'NYSE',   sector: 'Financials',       index: 'Dow' },
  { symbol: 'PG',    name: 'Procter & Gamble',      exchange: 'NYSE',   sector: 'Consumer Staples', index: 'Dow' },
  { symbol: 'MRK',   name: 'Merck & Co.',           exchange: 'NYSE',   sector: 'Healthcare',       index: 'Dow' },
  { symbol: 'MMM',   name: '3M Company',            exchange: 'NYSE',   sector: 'Industrials',      index: 'Dow' },
  { symbol: 'TRV',   name: 'Travelers Companies',   exchange: 'NYSE',   sector: 'Insurance',        index: 'Dow' },
  { symbol: 'CRM',   name: 'Salesforce Inc.',       exchange: 'NYSE',   sector: 'Technology',       index: 'Dow' },
  { symbol: 'HON',   name: 'Honeywell Intl.',       exchange: 'NASDAQ', sector: 'Industrials',      index: 'Dow' },
  { symbol: 'AMGN',  name: 'Amgen Inc.',            exchange: 'NASDAQ', sector: 'Biotech',          index: 'Dow' },
  { symbol: 'NKE',   name: 'Nike Inc.',             exchange: 'NYSE',   sector: 'Consumer',         index: 'Dow' },
  { symbol: 'DIS',   name: 'Walt Disney Co.',       exchange: 'NYSE',   sector: 'Media',            index: 'Dow' },
  { symbol: 'VZ',    name: 'Verizon Comms.',        exchange: 'NYSE',   sector: 'Telecom',          index: 'Dow' },
  { symbol: 'KO',    name: 'Coca-Cola Co.',         exchange: 'NYSE',   sector: 'Consumer Staples', index: 'Dow' },
  { symbol: 'INTC',  name: 'Intel Corp.',           exchange: 'NASDAQ', sector: 'Semiconductors',   index: 'Dow' },
  { symbol: 'WBA',   name: 'Walgreens Boots',       exchange: 'NASDAQ', sector: 'Retail',           index: 'Dow' },
  { symbol: 'DOW',   name: 'Dow Inc.',              exchange: 'NYSE',   sector: 'Chemicals',        index: 'Dow' },
  { symbol: 'RTX',   name: 'RTX Corp.',             exchange: 'NYSE',   sector: 'Aerospace',        index: 'Dow' },

  // ── S&P 500 / Nasdaq 100 additions ───────────────────────────────────────
  { symbol: 'TSM',   name: 'TSMC',                  exchange: 'NYSE',   sector: 'Semiconductors',   index: 'Nasdaq' },
  { symbol: 'ANET',  name: 'Arista Networks',       exchange: 'NYSE',   sector: 'Networking',       index: 'Nasdaq' },
  { symbol: 'PLTR',  name: 'Palantir Technologies', exchange: 'NASDAQ', sector: 'AI/Data',          index: 'Nasdaq' },
  { symbol: 'SPY',   name: 'SPDR S&P 500 ETF',     exchange: 'NYSE',   sector: 'Index ETF',        index: 'S&P 500' },
  { symbol: 'QQQ',   name: 'Nasdaq 100 ETF',        exchange: 'NASDAQ', sector: 'Index ETF',        index: 'Nasdaq' },
  { symbol: 'DIA',   name: 'Dow Jones ETF',         exchange: 'NYSE',   sector: 'Index ETF',        index: 'Dow' },
  { symbol: 'IWM',   name: 'Russell 2000 ETF',      exchange: 'NYSE',   sector: 'Index ETF',        index: 'S&P 500' },
  { symbol: 'NVDA',  name: 'NVIDIA Corp.',          exchange: 'NASDAQ', sector: 'Semiconductors',   index: 'Nasdaq' },
  { symbol: 'META',  name: 'Meta Platforms',        exchange: 'NASDAQ', sector: 'Technology',       index: 'Nasdaq' },
  { symbol: 'AMZN',  name: 'Amazon.com Inc.',       exchange: 'NASDAQ', sector: 'E-Commerce',       index: 'Nasdaq' },
  { symbol: 'GOOGL', name: 'Alphabet Inc.',         exchange: 'NASDAQ', sector: 'Technology',       index: 'Nasdaq' },
  { symbol: 'TSLA',  name: 'Tesla Inc.',            exchange: 'NASDAQ', sector: 'EV / Auto',        index: 'Nasdaq' },
  { symbol: 'AVGO',  name: 'Broadcom Inc.',         exchange: 'NASDAQ', sector: 'Semiconductors',   index: 'Nasdaq' },
  { symbol: 'LLY',   name: 'Eli Lilly & Co.',       exchange: 'NYSE',   sector: 'Pharma',           index: 'S&P 500' },
  { symbol: 'MA',    name: 'Mastercard Inc.',       exchange: 'NYSE',   sector: 'Financials',       index: 'S&P 500' },
  { symbol: 'COST',  name: 'Costco Wholesale',      exchange: 'NASDAQ', sector: 'Retail',           index: 'Nasdaq' },
  { symbol: 'NFLX',  name: 'Netflix Inc.',          exchange: 'NASDAQ', sector: 'Streaming',        index: 'Nasdaq' },
  { symbol: 'AMD',   name: 'Advanced Micro Devices',exchange: 'NASDAQ', sector: 'Semiconductors',   index: 'Nasdaq' },
  { symbol: 'PYPL',  name: 'PayPal Holdings',       exchange: 'NASDAQ', sector: 'Fintech',          index: 'Nasdaq' },
  { symbol: 'ORCL',  name: 'Oracle Corp.',          exchange: 'NYSE',   sector: 'Cloud / DB',       index: 'S&P 500' },
  { symbol: 'NOW',   name: 'ServiceNow',            exchange: 'NYSE',   sector: 'SaaS',             index: 'S&P 500' },
  { symbol: 'ADBE',  name: 'Adobe Inc.',            exchange: 'NASDAQ', sector: 'Software',         index: 'Nasdaq' },
  { symbol: 'QCOM',  name: 'Qualcomm Inc.',         exchange: 'NASDAQ', sector: 'Semiconductors',   index: 'Nasdaq' },
  { symbol: 'XOM',   name: 'ExxonMobil Corp.',      exchange: 'NYSE',   sector: 'Energy',           index: 'S&P 500' },
  { symbol: 'BAC',   name: 'Bank of America',       exchange: 'NYSE',   sector: 'Financials',       index: 'S&P 500' },
  { symbol: 'WFC',   name: 'Wells Fargo',           exchange: 'NYSE',   sector: 'Financials',       index: 'S&P 500' },
  { symbol: 'BRK-B', name: 'Berkshire Hathaway B',  exchange: 'NYSE',   sector: 'Conglomerate',     index: 'S&P 500' },
  { symbol: 'PFE',   name: 'Pfizer Inc.',           exchange: 'NYSE',   sector: 'Pharma',           index: 'S&P 500' },
  { symbol: 'ABBV',  name: 'AbbVie Inc.',           exchange: 'NYSE',   sector: 'Pharma',           index: 'S&P 500' },
  { symbol: 'TMO',   name: 'Thermo Fisher',         exchange: 'NYSE',   sector: 'Life Sciences',    index: 'S&P 500' },

  // ── Space & Aerospace ────────────────────────────────────────────────────
  // SpaceX IPO'd on NASDAQ June 12, 2026 under SPCX (IPO price $135, first close ~$161, $2T+ market cap)
  { symbol: 'SPCX',  name: 'SpaceX',                  exchange: 'NASDAQ', sector: 'Space/AI',         index: 'Space' },
  { symbol: 'UFO',   name: 'Procure Space ETF (UFO)',  exchange: 'NYSE',  sector: 'Space ETF',        index: 'Space' },
  { symbol: 'ROKT',  name: 'SPDR Kensho Final Frontiers', exchange: 'NYSE', sector: 'Space ETF',     index: 'Space' },
  { symbol: 'ITA',   name: 'iShares Aerospace & Defense ETF', exchange: 'BATS', sector: 'Aerospace ETF', index: 'Space' },
  { symbol: 'RKLB',  name: 'Rocket Lab USA',          exchange: 'NASDAQ', sector: 'Space Launch',     index: 'Space' },
  { symbol: 'ASTS',  name: 'AST SpaceMobile',         exchange: 'NASDAQ', sector: 'Space Telecom',    index: 'Space' },
  { symbol: 'SPCE',  name: 'Virgin Galactic',         exchange: 'NYSE',   sector: 'Space Tourism',    index: 'Space' },
  { symbol: 'PL',    name: 'Planet Labs PBC',         exchange: 'NYSE',   sector: 'Satellite Imaging', index: 'Space' },
  { symbol: 'BKSY',  name: 'BlackSky Technology',     exchange: 'NYSE',   sector: 'Satellite Imaging', index: 'Space' },
  { symbol: 'GSAT',  name: 'Globalstar Inc.',         exchange: 'NYSE',   sector: 'Satellite Comms',  index: 'Space' },
  { symbol: 'KTOS',  name: 'Kratos Defense',          exchange: 'NASDAQ', sector: 'Defense/Space',    index: 'Space' },
  { symbol: 'LMT',   name: 'Lockheed Martin',         exchange: 'NYSE',   sector: 'Defense',          index: 'Space' },
  { symbol: 'NOC',   name: 'Northrop Grumman',        exchange: 'NYSE',   sector: 'Defense',          index: 'Space' },
  { symbol: 'GD',    name: 'General Dynamics',        exchange: 'NYSE',   sector: 'Defense',          index: 'Space' },
  { symbol: 'TDY',   name: 'Teledyne Technologies',   exchange: 'NYSE',   sector: 'Aerospace Tech',   index: 'Space' },
  { symbol: 'GE',    name: 'GE Aerospace',            exchange: 'NYSE',   sector: 'Aerospace',        index: 'Space' },

  // ── Nuclear Energy ────────────────────────────────────────────────────────
  { symbol: 'CCJ',   name: 'Cameco Corp.',            exchange: 'NYSE',   sector: 'Uranium',          index: 'Nuclear' },
  { symbol: 'SMR',   name: 'NuScale Power',           exchange: 'NYSE',   sector: 'Nuclear SMR',      index: 'Nuclear' },
  { symbol: 'OKLO',  name: 'Oklo Inc.',               exchange: 'NYSE',   sector: 'Nuclear SMR',      index: 'Nuclear' },
  { symbol: 'CEG',   name: 'Constellation Energy',    exchange: 'NASDAQ', sector: 'Nuclear Power',    index: 'Nuclear' },
  { symbol: 'VST',   name: 'Vistra Corp.',            exchange: 'NYSE',   sector: 'Power/Nuclear',    index: 'Nuclear' },
  { symbol: 'URNM',  name: 'Sprott Uranium Miners ETF', exchange: 'NYSE', sector: 'Uranium ETF',     index: 'Nuclear' },

  // ── CLARITY Act Crypto ────────────────────────────────────────────────────
  { symbol: 'BTC-USD',  name: 'Bitcoin',            exchange: 'CRYPTO', sector: 'L1',               index: 'CLARITY' },
  { symbol: 'ETH-USD',  name: 'Ethereum',           exchange: 'CRYPTO', sector: 'L1',               index: 'CLARITY' },
  { symbol: 'SOL-USD',  name: 'Solana',             exchange: 'CRYPTO', sector: 'L1',               index: 'CLARITY' },
  { symbol: 'ADA-USD',  name: 'Cardano',            exchange: 'CRYPTO', sector: 'L1',               index: 'CLARITY' },
  { symbol: 'AVAX-USD', name: 'Avalanche',          exchange: 'CRYPTO', sector: 'L1',               index: 'CLARITY' },
  { symbol: 'DOT-USD',  name: 'Polkadot',           exchange: 'CRYPTO', sector: 'L0',               index: 'CLARITY' },
  { symbol: 'LINK-USD', name: 'Chainlink',          exchange: 'CRYPTO', sector: 'Oracle',           index: 'CLARITY' },
  { symbol: 'UNI-USD',  name: 'Uniswap',            exchange: 'CRYPTO', sector: 'DeFi',             index: 'CLARITY' },
  { symbol: 'AAVE-USD', name: 'Aave',               exchange: 'CRYPTO', sector: 'DeFi',             index: 'CLARITY' },
  { symbol: 'ARB-USD',  name: 'Arbitrum',           exchange: 'CRYPTO', sector: 'L2',               index: 'CLARITY' },
  { symbol: 'OP-USD',   name: 'Optimism',           exchange: 'CRYPTO', sector: 'L2',               index: 'CLARITY' },
  { symbol: 'MSTR',     name: 'MicroStrategy',      exchange: 'NASDAQ', sector: 'BTC Treasury',     index: 'CLARITY' },
];

export const DASHBOARD_SYMBOLS = DASHBOARD_ASSETS.map(a => a.symbol);
export const DASHBOARD_ASSET_MAP = Object.fromEntries(DASHBOARD_ASSETS.map(a => [a.symbol, a]));