import { ASSETS } from './assetCatalog';

// Additional assets beyond the base catalog — total target: ~500
const EXTRA = [
  // ── Healthcare & Biotech ──────────────────────────────────────────────────
  { symbol: 'ELV',  name: 'Elevance Health',         exchange: 'NYSE',   sector: 'Health Insurance',  asset_type: 'stock' },
  { symbol: 'CNC',  name: 'Centene Corp.',            exchange: 'NYSE',   sector: 'Health Insurance',  asset_type: 'stock' },
  { symbol: 'ISRG', name: 'Intuitive Surgical',       exchange: 'NASDAQ', sector: 'Medical Devices',   asset_type: 'stock' },
  { symbol: 'EW',   name: 'Edwards Lifesciences',     exchange: 'NYSE',   sector: 'Medical Devices',   asset_type: 'stock' },
  { symbol: 'BDX',  name: 'Becton Dickinson',         exchange: 'NYSE',   sector: 'Medical Devices',   asset_type: 'stock' },
  { symbol: 'DXCM', name: 'Dexcom Inc.',              exchange: 'NASDAQ', sector: 'Medical Devices',   asset_type: 'stock' },
  { symbol: 'IQV',  name: 'IQVIA Holdings',           exchange: 'NYSE',   sector: 'Life Sciences',     asset_type: 'stock' },
  { symbol: 'A',    name: 'Agilent Technologies',     exchange: 'NYSE',   sector: 'Life Sciences',     asset_type: 'stock' },
  { symbol: 'IDXX', name: 'IDEXX Laboratories',       exchange: 'NASDAQ', sector: 'Vet Diagnostics',   asset_type: 'stock' },
  { symbol: 'AMGN', name: 'Amgen Inc.',               exchange: 'NASDAQ', sector: 'Biotech',           asset_type: 'stock' },
  { symbol: 'HIMS', name: 'Hims & Hers Health',       exchange: 'NYSE',   sector: 'HealthTech',        asset_type: 'stock' },
  // ── Consumer ─────────────────────────────────────────────────────────────
  { symbol: 'LULU', name: 'Lululemon Athletica',      exchange: 'NASDAQ', sector: 'Apparel',           asset_type: 'stock' },
  { symbol: 'ULTA', name: 'Ulta Beauty',              exchange: 'NASDAQ', sector: 'Retail',            asset_type: 'stock' },
  { symbol: 'DG',   name: 'Dollar General',           exchange: 'NYSE',   sector: 'Retail',            asset_type: 'stock' },
  { symbol: 'DLTR', name: 'Dollar Tree',              exchange: 'NASDAQ', sector: 'Retail',            asset_type: 'stock' },
  { symbol: 'AZO',  name: 'AutoZone Inc.',            exchange: 'NYSE',   sector: 'Auto Parts',        asset_type: 'stock' },
  { symbol: 'ORLY', name: "O'Reilly Auto Parts",      exchange: 'NASDAQ', sector: 'Auto Parts',        asset_type: 'stock' },
  { symbol: 'CMG',  name: 'Chipotle Mexican Grill',   exchange: 'NYSE',   sector: 'Restaurants',       asset_type: 'stock' },
  { symbol: 'QSR',  name: 'Restaurant Brands Intl.',  exchange: 'NYSE',   sector: 'Restaurants',       asset_type: 'stock' },
  { symbol: 'CAVA', name: 'CAVA Group',               exchange: 'NYSE',   sector: 'Restaurants',       asset_type: 'stock' },
  { symbol: 'EL',   name: 'Estee Lauder',             exchange: 'NYSE',   sector: 'Beauty',            asset_type: 'stock' },
  { symbol: 'GIS',  name: 'General Mills',            exchange: 'NYSE',   sector: 'Consumer Staples',  asset_type: 'stock' },
  { symbol: 'HSY',  name: 'Hershey Co.',              exchange: 'NYSE',   sector: 'Consumer Staples',  asset_type: 'stock' },
  { symbol: 'SYY',  name: 'Sysco Corp.',              exchange: 'NYSE',   sector: 'Food Distribution', asset_type: 'stock' },
  { symbol: 'WSM',  name: 'Williams-Sonoma',          exchange: 'NYSE',   sector: 'Home Furnishings',  asset_type: 'stock' },
  { symbol: 'CELH', name: 'Celsius Holdings',         exchange: 'NASDAQ', sector: 'Beverages',         asset_type: 'stock' },
  // ── Industrials & Materials ───────────────────────────────────────────────
  { symbol: 'ITW',  name: 'Illinois Tool Works',      exchange: 'NYSE',   sector: 'Industrials',       asset_type: 'stock' },
  { symbol: 'PH',   name: 'Parker-Hannifin',          exchange: 'NYSE',   sector: 'Industrials',       asset_type: 'stock' },
  { symbol: 'FAST', name: 'Fastenal Co.',             exchange: 'NASDAQ', sector: 'Industrials',       asset_type: 'stock' },
  { symbol: 'GWW',  name: 'W.W. Grainger',           exchange: 'NYSE',   sector: 'Industrials',       asset_type: 'stock' },
  { symbol: 'VRSK', name: 'Verisk Analytics',         exchange: 'NASDAQ', sector: 'Analytics',         asset_type: 'stock' },
  { symbol: 'FCX',  name: 'Freeport-McMoRan',         exchange: 'NYSE',   sector: 'Mining',            asset_type: 'stock' },
  { symbol: 'NEM',  name: 'Newmont Corp.',            exchange: 'NYSE',   sector: 'Gold Mining',       asset_type: 'stock' },
  { symbol: 'GOLD', name: 'Barrick Gold',             exchange: 'NYSE',   sector: 'Gold Mining',       asset_type: 'stock' },
  { symbol: 'NUE',  name: 'Nucor Corp.',              exchange: 'NYSE',   sector: 'Steel',             asset_type: 'stock' },
  { symbol: 'STLD', name: 'Steel Dynamics',           exchange: 'NASDAQ', sector: 'Steel',             asset_type: 'stock' },
  { symbol: 'CF',   name: 'CF Industries',            exchange: 'NYSE',   sector: 'Fertilizers',       asset_type: 'stock' },
  { symbol: 'DOW',  name: 'Dow Inc.',                 exchange: 'NYSE',   sector: 'Chemicals',         asset_type: 'stock' },
  { symbol: 'SHW',  name: 'Sherwin-Williams',         exchange: 'NYSE',   sector: 'Specialty Chemicals',asset_type: 'stock' },
  { symbol: 'PPG',  name: 'PPG Industries',           exchange: 'NYSE',   sector: 'Specialty Chemicals',asset_type: 'stock' },
  // ── Energy ───────────────────────────────────────────────────────────────
  { symbol: 'EOG',  name: 'EOG Resources',            exchange: 'NYSE',   sector: 'Energy',            asset_type: 'stock' },
  { symbol: 'DVN',  name: 'Devon Energy',             exchange: 'NYSE',   sector: 'Energy',            asset_type: 'stock' },
  { symbol: 'FANG', name: 'Diamondback Energy',       exchange: 'NASDAQ', sector: 'Energy',            asset_type: 'stock' },
  { symbol: 'HES',  name: 'Hess Corp.',               exchange: 'NYSE',   sector: 'Energy',            asset_type: 'stock' },
  { symbol: 'BKR',  name: 'Baker Hughes',             exchange: 'NASDAQ', sector: 'Energy Services',   asset_type: 'stock' },
  { symbol: 'KMI',  name: 'Kinder Morgan',            exchange: 'NYSE',   sector: 'Midstream Energy',  asset_type: 'stock' },
  { symbol: 'WMB',  name: 'Williams Companies',       exchange: 'NYSE',   sector: 'Midstream Energy',  asset_type: 'stock' },
  { symbol: 'LNG',  name: 'Cheniere Energy',          exchange: 'NYSE',   sector: 'LNG',               asset_type: 'stock' },
  // ── Financials ───────────────────────────────────────────────────────────
  { symbol: 'RF',   name: 'Regions Financial',        exchange: 'NYSE',   sector: 'Banking',           asset_type: 'stock' },
  { symbol: 'FITB', name: 'Fifth Third Bancorp',      exchange: 'NASDAQ', sector: 'Banking',           asset_type: 'stock' },
  { symbol: 'ALLY', name: 'Ally Financial',           exchange: 'NYSE',   sector: 'Auto Finance',      asset_type: 'stock' },
  { symbol: 'SQ',   name: 'Block Inc.',               exchange: 'NYSE',   sector: 'Fintech',           asset_type: 'stock' },
  { symbol: 'SPGI', name: 'S&P Global Inc.',          exchange: 'NYSE',   sector: 'Financial Services', asset_type: 'stock' },
  { symbol: 'MCO',  name: "Moody's Corp.",            exchange: 'NYSE',   sector: 'Financial Services', asset_type: 'stock' },
  { symbol: 'FISV', name: 'Fiserv Inc.',              exchange: 'NASDAQ', sector: 'Fintech',           asset_type: 'stock' },
  // ── Tech ─────────────────────────────────────────────────────────────────
  { symbol: 'ANET', name: 'Arista Networks',           exchange: 'NYSE',   sector: 'Networking',        asset_type: 'stock' },
  { symbol: 'APP',  name: 'AppLovin Corp.',           exchange: 'NASDAQ', sector: 'AdTech/AI',         asset_type: 'stock' },
  { symbol: 'ARM',  name: 'ARM Holdings',             exchange: 'NASDAQ', sector: 'Semiconductors',    asset_type: 'stock' },
  { symbol: 'KLAC', name: 'KLA Corp.',                exchange: 'NASDAQ', sector: 'Semiconductors',    asset_type: 'stock' },
  { symbol: 'NXPI', name: 'NXP Semiconductors',       exchange: 'NASDAQ', sector: 'Semiconductors',    asset_type: 'stock' },
  { symbol: 'ON',   name: 'ON Semiconductor',         exchange: 'NASDAQ', sector: 'Semiconductors',    asset_type: 'stock' },
  { symbol: 'MSI',  name: 'Motorola Solutions',       exchange: 'NYSE',   sector: 'Communications',    asset_type: 'stock' },
  { symbol: 'RKLB', name: 'Rocket Lab USA',           exchange: 'NASDAQ', sector: 'Space',             asset_type: 'stock' },
  { symbol: 'ASTS', name: 'AST SpaceMobile',          exchange: 'NASDAQ', sector: 'Space Telecom',     asset_type: 'stock' },
  // SpaceX IPO — NASDAQ June 12, 2026
  { symbol: 'SPCX', name: 'SpaceX (Space Exploration Technologies)', exchange: 'NASDAQ', sector: 'Space/AI', asset_type: 'stock' },
  { symbol: 'UFO',  name: 'Procure Space ETF (UFO)',  exchange: 'NYSE',   sector: 'Space ETF',         asset_type: 'etf' },
  { symbol: 'ROKT', name: 'SPDR Kensho Final Frontiers', exchange: 'NYSE', sector: 'Space ETF',        asset_type: 'etf' },
  { symbol: 'ITA',  name: 'iShares Aerospace & Defense ETF', exchange: 'BATS', sector: 'Aerospace ETF',asset_type: 'etf' },
  { symbol: 'PPA',  name: 'Invesco Aerospace & Defense ETF', exchange: 'NASDAQ', sector: 'Aerospace ETF', asset_type: 'etf' },
  { symbol: 'XAR',  name: 'SPDR S&P Aerospace & Defense ETF', exchange: 'NYSE', sector: 'Aerospace ETF', asset_type: 'etf' },
  { symbol: 'SPCE', name: 'Virgin Galactic',          exchange: 'NYSE',   sector: 'Space Tourism',     asset_type: 'stock' },
  { symbol: 'PL',   name: 'Planet Labs PBC',          exchange: 'NYSE',   sector: 'Satellite Imaging', asset_type: 'stock' },
  { symbol: 'BKSY', name: 'BlackSky Technology',      exchange: 'NYSE',   sector: 'Satellite Imaging', asset_type: 'stock' },
  { symbol: 'SPIR', name: 'Spire Global Inc.',        exchange: 'NYSE',   sector: 'Satellite Data',    asset_type: 'stock' },
  { symbol: 'KTOS', name: 'Kratos Defense',           exchange: 'NASDAQ', sector: 'Defense/Space',     asset_type: 'stock' },
  { symbol: 'GSAT', name: 'Globalstar Inc.',          exchange: 'NYSE',   sector: 'Satellite Comms',   asset_type: 'stock' },
  { symbol: 'VSAT', name: 'ViaSat Inc.',              exchange: 'NASDAQ', sector: 'Satellite Comms',   asset_type: 'stock' },
  { symbol: 'TDY',  name: 'Teledyne Technologies',    exchange: 'NYSE',   sector: 'Aerospace Tech',    asset_type: 'stock' },
  { symbol: 'VRT',  name: 'Vertiv Holdings',          exchange: 'NYSE',   sector: 'Data Center Infra', asset_type: 'stock' },
  { symbol: 'CCJ',  name: 'Cameco Corp.',             exchange: 'NYSE',   sector: 'Uranium',           asset_type: 'stock' },
  { symbol: 'SMR',  name: 'NuScale Power',            exchange: 'NYSE',   sector: 'Nuclear SMR',       asset_type: 'stock' },
  { symbol: 'OKLO', name: 'Oklo Inc.',                exchange: 'NYSE',   sector: 'Nuclear SMR',       asset_type: 'stock' },
  { symbol: 'CEG',  name: 'Constellation Energy',     exchange: 'NASDAQ', sector: 'Nuclear Power',     asset_type: 'stock' },
  { symbol: 'URNM', name: 'Sprott Uranium Miners ETF',exchange: 'NYSE',   sector: 'Uranium ETF',       asset_type: 'etf' },
  { symbol: 'URA',  name: 'Global X Uranium ETF',     exchange: 'NYSE',   sector: 'Uranium ETF',       asset_type: 'etf' },
  { symbol: 'CRSP', name: 'CRISPR Therapeutics',      exchange: 'NASDAQ', sector: 'Gene Editing',      asset_type: 'stock' },
  { symbol: 'CDNS', name: 'Cadence Design Systems',   exchange: 'NASDAQ', sector: 'EDA Software',      asset_type: 'stock' },
  { symbol: 'SNPS', name: 'Synopsys Inc.',            exchange: 'NASDAQ', sector: 'EDA Software',      asset_type: 'stock' },
  // ── REITs ─────────────────────────────────────────────────────────────────
  { symbol: 'PSA',  name: 'Public Storage',           exchange: 'NYSE',   sector: 'REIT',              asset_type: 'stock' },
  { symbol: 'AVB',  name: 'AvalonBay Communities',    exchange: 'NYSE',   sector: 'Residential REIT',  asset_type: 'stock' },
  { symbol: 'EQR',  name: 'Equity Residential',       exchange: 'NYSE',   sector: 'Residential REIT',  asset_type: 'stock' },
  { symbol: 'PSA',  name: 'Public Storage',           exchange: 'NYSE',   sector: 'Self Storage REIT', asset_type: 'stock' },
  // ── More Crypto ───────────────────────────────────────────────────────────
  { symbol: 'TON-USD',   name: 'Toncoin',             exchange: 'CRYPTO', sector: 'L1',            asset_type: 'crypto' },
  { symbol: 'TAO-USD',   name: 'Bittensor',           exchange: 'CRYPTO', sector: 'AI',            asset_type: 'crypto' },
  { symbol: 'KAS-USD',   name: 'Kaspa',               exchange: 'CRYPTO', sector: 'L1',            asset_type: 'crypto' },
  { symbol: 'XMR-USD',   name: 'Monero',              exchange: 'CRYPTO', sector: 'Privacy',       asset_type: 'crypto' },
  { symbol: 'TRX-USD',   name: 'Tron',                exchange: 'CRYPTO', sector: 'L1',            asset_type: 'crypto' },
  { symbol: 'HBAR-USD',  name: 'Hedera',              exchange: 'CRYPTO', sector: 'L1',            asset_type: 'crypto' },
  { symbol: 'ONDO-USD',  name: 'Ondo Finance',        exchange: 'CRYPTO', sector: 'RWA',           asset_type: 'crypto' },
  { symbol: 'ENS-USD',   name: 'Ethereum Name Svc',   exchange: 'CRYPTO', sector: 'Infrastructure',asset_type: 'crypto' },
  { symbol: 'BEAM-USD',  name: 'Beam',                exchange: 'CRYPTO', sector: 'Gaming',        asset_type: 'crypto' },
  { symbol: 'GALA-USD',  name: 'Gala',                exchange: 'CRYPTO', sector: 'Gaming',        asset_type: 'crypto' },
  { symbol: 'STX-USD',   name: 'Stacks (Bitcoin L2)', exchange: 'CRYPTO', sector: 'Bitcoin L2',   asset_type: 'crypto' },
  { symbol: 'BLUR-USD',  name: 'Blur NFT',            exchange: 'CRYPTO', sector: 'NFT',           asset_type: 'crypto' },
  { symbol: 'MAGIC-USD', name: 'Magic (Treasure)',    exchange: 'CRYPTO', sector: 'Gaming',        asset_type: 'crypto' },
  { symbol: 'LOOKS-USD', name: 'LooksRare',           exchange: 'CRYPTO', sector: 'NFT',           asset_type: 'crypto' },
  // ── International ETFs ────────────────────────────────────────────────────
  { symbol: 'EWT',  name: 'Taiwan ETF (iShares)',     exchange: 'NYSE',   sector: 'Intl ETF',      asset_type: 'etf' },
  { symbol: 'EWW',  name: 'Mexico ETF (iShares)',     exchange: 'NYSE',   sector: 'Intl ETF',      asset_type: 'etf' },
  { symbol: 'EWS',  name: 'Singapore ETF (iShares)',  exchange: 'NYSE',   sector: 'Intl ETF',      asset_type: 'etf' },
  { symbol: 'EWP',  name: 'Spain ETF (iShares)',      exchange: 'NYSE',   sector: 'Intl ETF',      asset_type: 'etf' },
  { symbol: 'EWQ',  name: 'France ETF (iShares)',     exchange: 'NYSE',   sector: 'Intl ETF',      asset_type: 'etf' },
  { symbol: 'EWD',  name: 'Sweden ETF (iShares)',     exchange: 'NYSE',   sector: 'Intl ETF',      asset_type: 'etf' },
  { symbol: 'ARGT', name: 'Argentina ETF',            exchange: 'NYSE',   sector: 'Intl ETF',      asset_type: 'etf' },
  { symbol: 'ECH',  name: 'Chile ETF',                exchange: 'NYSE',   sector: 'Intl ETF',      asset_type: 'etf' },
  { symbol: 'EZA',  name: 'South Africa ETF',         exchange: 'NYSE',   sector: 'Intl ETF',      asset_type: 'etf' },
  { symbol: 'EPHE', name: 'Philippines ETF',          exchange: 'NYSE',   sector: 'Intl ETF',      asset_type: 'etf' },
  { symbol: 'THD',  name: 'Thailand ETF',             exchange: 'NYSE',   sector: 'Intl ETF',      asset_type: 'etf' },
  { symbol: 'EIDO', name: 'Indonesia ETF',            exchange: 'NYSE',   sector: 'Intl ETF',      asset_type: 'etf' },
  // ── Sector ETFs ───────────────────────────────────────────────────────────
  { symbol: 'XLF',  name: 'Financials Sector SPDR',   exchange: 'NYSE',   sector: 'Sector ETF',    asset_type: 'etf' },
  { symbol: 'XLK',  name: 'Technology Sector SPDR',   exchange: 'NYSE',   sector: 'Sector ETF',    asset_type: 'etf' },
  { symbol: 'XLE',  name: 'Energy Sector SPDR',       exchange: 'NYSE',   sector: 'Sector ETF',    asset_type: 'etf' },
  { symbol: 'XLV',  name: 'Health Care Sector SPDR',  exchange: 'NYSE',   sector: 'Sector ETF',    asset_type: 'etf' },
  { symbol: 'XLI',  name: 'Industrials Sector SPDR',  exchange: 'NYSE',   sector: 'Sector ETF',    asset_type: 'etf' },
  { symbol: 'XLP',  name: 'Consumer Staples SPDR',    exchange: 'NYSE',   sector: 'Sector ETF',    asset_type: 'etf' },
  { symbol: 'XLY',  name: 'Consumer Disc. SPDR',      exchange: 'NYSE',   sector: 'Sector ETF',    asset_type: 'etf' },
  { symbol: 'XLU',  name: 'Utilities Sector SPDR',    exchange: 'NYSE',   sector: 'Sector ETF',    asset_type: 'etf' },
  { symbol: 'XLRE', name: 'Real Estate SPDR',         exchange: 'NYSE',   sector: 'Sector ETF',    asset_type: 'etf' },
  { symbol: 'XLB',  name: 'Materials Sector SPDR',    exchange: 'NYSE',   sector: 'Sector ETF',    asset_type: 'etf' },
  { symbol: 'XLC',  name: 'Communication Svcs SPDR',  exchange: 'NYSE',   sector: 'Sector ETF',    asset_type: 'etf' },
  { symbol: 'SOXX', name: 'iShares Semis ETF',        exchange: 'NASDAQ', sector: 'Sector ETF',    asset_type: 'etf' },
  { symbol: 'HACK', name: 'Cybersecurity ETF',        exchange: 'NYSE',   sector: 'Sector ETF',    asset_type: 'etf' },
  { symbol: 'BOTZ', name: 'Robotics & AI ETF',        exchange: 'NASDAQ', sector: 'Sector ETF',    asset_type: 'etf' },
  { symbol: 'KWEB', name: 'China Internet ETF',       exchange: 'NYSE',   sector: 'Sector ETF',    asset_type: 'etf' },
  // ── Crypto ETFs ───────────────────────────────────────────────────────────
  { symbol: 'IBIT', name: 'iShares Bitcoin Trust',    exchange: 'NASDAQ', sector: 'Crypto ETF',    asset_type: 'etf' },
  { symbol: 'FBTC', name: 'Fidelity Bitcoin ETF',     exchange: 'NASDAQ', sector: 'Crypto ETF',    asset_type: 'etf' },
  { symbol: 'ETHA', name: 'iShares Ethereum Trust',   exchange: 'NASDAQ', sector: 'Crypto ETF',    asset_type: 'etf' },
  { symbol: 'BITO', name: 'Bitcoin Strategy ETF',     exchange: 'NYSE',   sector: 'Crypto ETF',    asset_type: 'etf' },
  { symbol: 'MSTX', name: 'MicroStrategy 2x Bull',    exchange: 'NASDAQ', sector: 'Leveraged ETF', asset_type: 'etf' },
  { symbol: 'NVDL', name: 'NVIDIA 2x Bull ETF',       exchange: 'NYSE',   sector: 'Leveraged ETF', asset_type: 'etf' },
  { symbol: 'TSLL', name: 'Tesla 2x Bull ETF',        exchange: 'NASDAQ', sector: 'Leveraged ETF', asset_type: 'etf' },
  // ── Bond & Commodity ETFs ─────────────────────────────────────────────────
  { symbol: 'TLT',  name: 'iShares 20+ Yr Treasury',  exchange: 'NASDAQ', sector: 'Bond ETF',      asset_type: 'etf' },
  { symbol: 'IEF',  name: 'iShares 7-10 Yr Treasury', exchange: 'NASDAQ', sector: 'Bond ETF',      asset_type: 'etf' },
  { symbol: 'HYG',  name: 'iShares High Yield Bond',  exchange: 'NYSE',   sector: 'Bond ETF',      asset_type: 'etf' },
  { symbol: 'LQD',  name: 'iShares Investment Grade',  exchange: 'NYSE',   sector: 'Bond ETF',      asset_type: 'etf' },
  { symbol: 'AGG',  name: 'iShares US Aggregate Bond', exchange: 'NYSE',   sector: 'Bond ETF',      asset_type: 'etf' },
  { symbol: 'TIP',  name: 'iShares TIPS Bond ETF',     exchange: 'NYSE',   sector: 'Bond ETF',      asset_type: 'etf' },
  { symbol: 'PDBC', name: 'Invesco Commodities ETF',   exchange: 'NASDAQ', sector: 'Commodity ETF', asset_type: 'etf' },
  { symbol: 'COMT', name: 'iShares GSCI Commodity',   exchange: 'NYSE',   sector: 'Commodity ETF', asset_type: 'etf' },
  { symbol: 'WEAT', name: 'Wheat ETF',                 exchange: 'NYSE',   sector: 'Commodity ETF', asset_type: 'etf' },
  { symbol: 'CORN', name: 'Corn ETF',                  exchange: 'NYSE',   sector: 'Commodity ETF', asset_type: 'etf' },
  { symbol: 'SOYB', name: 'Soybeans ETF',              exchange: 'NYSE',   sector: 'Commodity ETF', asset_type: 'etf' },
  { symbol: 'UNG',  name: 'US Natural Gas Fund',       exchange: 'NYSE',   sector: 'Commodity ETF', asset_type: 'etf' },
  { symbol: 'PPLT', name: 'Platinum ETF',              exchange: 'NYSE',   sector: 'Commodity ETF', asset_type: 'etf' },
  { symbol: 'PALL', name: 'Palladium ETF',             exchange: 'NYSE',   sector: 'Commodity ETF', asset_type: 'etf' },
];

// Deduplicate by symbol
const seen = new Set();
const all = [...ASSETS, ...EXTRA].filter(a => {
  if (seen.has(a.symbol)) return false;
  seen.add(a.symbol);
  return true;
});

export const SCREENER_ASSETS = all;
export const SCREENER_SYMBOLS = all.map(a => a.symbol);
export const SCREENER_ASSET_MAP = Object.fromEntries(all.map(a => [a.symbol, a]));